// This file is GENERATED by `cargo xtask migrate-c-tests --algo x509-parse`.
// DO NOT EDIT BY HAND. Source: openhitls C SDV pki/cert + pki/csr `.data`.
//
// Generator: docs/c-test-migration-plan.md Phase C (xtask).
// Fixtures: tests/vectors/c-asn1-fixtures/ (mirrored openHiTLS testdata).

#![cfg(feature = "x509")]

use hitls_pki::x509::{Certificate, CertificateRequest};

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse xmss cert pem
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 5, X.509 cert parse KAT)
#[test]
fn tc_line5_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/xmss_cert/end.pem"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(Certificate::from_pem(pem).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse xmss cert der
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 8, X.509 cert parse KAT)
#[test]
fn tc_line8_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/xmss_cert/end.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse ed25519 cert pem
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 11, X.509 cert parse KAT)
#[test]
fn tc_line11_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/ed25519/ed25519.ca.pem"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(Certificate::from_pem(pem).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse ed25519 cert der
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 14, X.509 cert parse KAT)
#[test]
fn tc_line14_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/ed25519/ed25519.ca.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse x25519 ee cert pem
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 20, X.509 cert parse KAT)
#[test]
fn tc_line20_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/x25519/x25519.ee.pem"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(Certificate::from_pem(pem).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse x25519 ee cert der
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 23, X.509 cert parse KAT)
#[test]
fn tc_line23_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/x25519/x25519.ee.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse pem cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 29, X.509 cert parse KAT)
#[test]
fn tc_line29_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/pem/cert/ca.pem"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(Certificate::from_pem(pem).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse ecc p384 v3 ca cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 38, X.509 cert parse KAT)
#[test]
fn tc_line38_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/nist384ca.crt"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa pss v3 ca cert, any is null
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 41, X.509 cert parse KAT)
#[test]
fn tc_line41_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa2048ssa-pss.crt"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse sha256 rsa v1 ca, any is null
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 44, X.509 cert parse KAT)
#[test]
fn tc_line44_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/sha256Rsaca.crt"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 with key usage sha256 rsa v3 ca
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 47, X.509 cert parse KAT)
#[test]
fn tc_line47_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/cawithkeyusage.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_ca cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 50, X.509 cert parse KAT)
#[test]
fn tc_line50_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_cert/ca.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_ca.mul cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 53, X.509 cert parse KAT)
#[test]
fn tc_line53_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_cert/ca.mul.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_ca.noCRL cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 56, X.509 cert parse KAT)
#[test]
fn tc_line56_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_cert/ca.noCRL.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_ca.notCA cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 59, X.509 cert parse KAT)
#[test]
fn tc_line59_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_cert/ca.notCA.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_ca.v1 cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 62, X.509 cert parse KAT)
#[test]
fn tc_line62_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_cert/ca.v1.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_end cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 65, X.509 cert parse KAT)
#[test]
fn tc_line65_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_cert/end.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_end.mul cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 68, X.509 cert parse KAT)
#[test]
fn tc_line68_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_cert/end.mul.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_end.noCRL cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 71, X.509 cert parse KAT)
#[test]
fn tc_line71_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_cert/end.noCRL.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_end.notCA cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 74, X.509 cert parse KAT)
#[test]
fn tc_line74_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_cert/end.notCA.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_end.v1 cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 77, X.509 cert parse KAT)
#[test]
fn tc_line77_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_cert/end.v1.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_end2.mul cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 80, X.509 cert parse KAT)
#[test]
fn tc_line80_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_cert/end2.mul.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_end3.mul cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 83, X.509 cert parse KAT)
#[test]
fn tc_line83_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_cert/end3.mul.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_inter cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 86, X.509 cert parse KAT)
#[test]
fn tc_line86_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_cert/inter.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_inter.mul cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 89, X.509 cert parse KAT)
#[test]
fn tc_line89_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_cert/inter.mul.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_inter.noCRL cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 92, X.509 cert parse KAT)
#[test]
fn tc_line92_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_cert/inter.noCRL.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_inter.notCA cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 95, X.509 cert parse KAT)
#[test]
fn tc_line95_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_cert/inter.notCA.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_inter.v1 cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 98, X.509 cert parse KAT)
#[test]
fn tc_line98_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_cert/inter.v1.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse ecdsa_ca cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 102, X.509 cert parse KAT)
#[test]
fn tc_line102_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/ecdsa_cert/ca.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse ecdsa_ca.mul cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 105, X.509 cert parse KAT)
#[test]
fn tc_line105_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/ecdsa_cert/ca.mul.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse ecdsa_ca.noCRL cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 108, X.509 cert parse KAT)
#[test]
fn tc_line108_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/ecdsa_cert/ca.noCRL.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse ecdsa_ca.notCA cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 111, X.509 cert parse KAT)
#[test]
fn tc_line111_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/ecdsa_cert/ca.notCA.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse ecdsa_ca.v1 cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 114, X.509 cert parse KAT)
#[test]
fn tc_line114_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/ecdsa_cert/ca.v1.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse ecdsa_end cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 117, X.509 cert parse KAT)
#[test]
fn tc_line117_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/ecdsa_cert/end.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse ecdsa_end.mul cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 120, X.509 cert parse KAT)
#[test]
fn tc_line120_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/ecdsa_cert/end.mul.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse ecdsa_end.noCRL cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 123, X.509 cert parse KAT)
#[test]
fn tc_line123_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/ecdsa_cert/end.noCRL.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse ecdsa_end.notCA cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 126, X.509 cert parse KAT)
#[test]
fn tc_line126_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/ecdsa_cert/end.notCA.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse ecdsa_end.v1 cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 129, X.509 cert parse KAT)
#[test]
fn tc_line129_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/ecdsa_cert/end.v1.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse ecdsa_end2.mul cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 132, X.509 cert parse KAT)
#[test]
fn tc_line132_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/ecdsa_cert/end2.mul.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse ecdsa_end3.mul cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 135, X.509 cert parse KAT)
#[test]
fn tc_line135_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/ecdsa_cert/end3.mul.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse ecdsa_inter cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 138, X.509 cert parse KAT)
#[test]
fn tc_line138_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/ecdsa_cert/inter.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse ecdsa_inter.mul cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 141, X.509 cert parse KAT)
#[test]
fn tc_line141_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/ecdsa_cert/inter.mul.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse ecdsa_inter.noCRL cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 144, X.509 cert parse KAT)
#[test]
fn tc_line144_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/ecdsa_cert/inter.noCRL.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse ecdsa_inter.notCA cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 147, X.509 cert parse KAT)
#[test]
fn tc_line147_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/ecdsa_cert/inter.notCA.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse ecdsa_inter.v1 cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 150, X.509 cert parse KAT)
#[test]
fn tc_line150_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/ecdsa_cert/inter.v1.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_ecc_ca cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 153, X.509 cert parse KAT)
#[test]
fn tc_line153_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_ecc_cert/ca.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_ecc_ca.mul cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 156, X.509 cert parse KAT)
#[test]
fn tc_line156_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_ecc_cert/ca.mul.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_ecc_ca.noCRL cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 159, X.509 cert parse KAT)
#[test]
fn tc_line159_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_ecc_cert/ca.noCRL.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_ecc_ca.notCA cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 162, X.509 cert parse KAT)
#[test]
fn tc_line162_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_ecc_cert/ca.notCA.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_ecc_ca.v1 cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 165, X.509 cert parse KAT)
#[test]
fn tc_line165_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_ecc_cert/ca.v1.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_ecc_end cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 168, X.509 cert parse KAT)
#[test]
fn tc_line168_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_ecc_cert/end.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_ecc_end.mul cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 171, X.509 cert parse KAT)
#[test]
fn tc_line171_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_ecc_cert/end.mul.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_ecc_end.noCRL cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 174, X.509 cert parse KAT)
#[test]
fn tc_line174_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_ecc_cert/end.noCRL.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_ecc_end.notCA cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 177, X.509 cert parse KAT)
#[test]
fn tc_line177_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_ecc_cert/end.notCA.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_ecc_end.v1 cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 180, X.509 cert parse KAT)
#[test]
fn tc_line180_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_ecc_cert/end.v1.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_ecc_end2.mul cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 183, X.509 cert parse KAT)
#[test]
fn tc_line183_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_ecc_cert/end2.mul.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_ecc_end3.mul cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 186, X.509 cert parse KAT)
#[test]
fn tc_line186_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_ecc_cert/end3.mul.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_ecc_inter cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 189, X.509 cert parse KAT)
#[test]
fn tc_line189_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_ecc_cert/inter.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_ecc_inter.mul cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 192, X.509 cert parse KAT)
#[test]
fn tc_line192_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_ecc_cert/inter.mul.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_ecc_inter.noCRL cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 195, X.509 cert parse KAT)
#[test]
fn tc_line195_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_ecc_cert/inter.noCRL.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_ecc_inter.notCA cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 198, X.509 cert parse KAT)
#[test]
fn tc_line198_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_ecc_cert/inter.notCA.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_ecc_inter.v1 cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 201, X.509 cert parse KAT)
#[test]
fn tc_line201_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_ecc_cert/inter.v1.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_pss_ca cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 205, X.509 cert parse KAT)
#[test]
fn tc_line205_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_pss_cert/ca.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_pss_ca.mul cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 208, X.509 cert parse KAT)
#[test]
fn tc_line208_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_pss_cert/ca.mul.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_pss_ca.noCRL cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 211, X.509 cert parse KAT)
#[test]
fn tc_line211_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_pss_cert/ca.noCRL.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_pss_ca.notCA cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 214, X.509 cert parse KAT)
#[test]
fn tc_line214_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_pss_cert/ca.notCA.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_pss_ca.v1 cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 217, X.509 cert parse KAT)
#[test]
fn tc_line217_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_pss_cert/ca.v1.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_pss_end cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 220, X.509 cert parse KAT)
#[test]
fn tc_line220_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_pss_cert/end.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_pss_end.mul cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 223, X.509 cert parse KAT)
#[test]
fn tc_line223_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_pss_cert/end.mul.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_pss_end.noCRL cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 226, X.509 cert parse KAT)
#[test]
fn tc_line226_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_pss_cert/end.noCRL.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_pss_end.notCA cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 229, X.509 cert parse KAT)
#[test]
fn tc_line229_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_pss_cert/end.notCA.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_pss_end.v1 cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 232, X.509 cert parse KAT)
#[test]
fn tc_line232_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_pss_cert/end.v1.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_pss_end2.mul cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 235, X.509 cert parse KAT)
#[test]
fn tc_line235_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_pss_cert/end2.mul.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_pss_end3.mul cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 238, X.509 cert parse KAT)
#[test]
fn tc_line238_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_pss_cert/end3.mul.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_pss_inter cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 241, X.509 cert parse KAT)
#[test]
fn tc_line241_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_pss_cert/inter.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_pss_inter.mul cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 244, X.509 cert parse KAT)
#[test]
fn tc_line244_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_pss_cert/inter.mul.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_pss_inter.noCRL cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 247, X.509 cert parse KAT)
#[test]
fn tc_line247_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_pss_cert/inter.noCRL.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_pss_inter.notCA cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 250, X.509 cert parse KAT)
#[test]
fn tc_line250_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_pss_cert/inter.notCA.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse rsa_pss_inter.v1 cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 253, X.509 cert parse KAT)
#[test]
fn tc_line253_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/rsa_pss_cert/inter.v1.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse sm2_ca cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 257, X.509 cert parse KAT)
#[test]
fn tc_line257_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/sm2_cert/ca.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse sm2_ca.mul cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 260, X.509 cert parse KAT)
#[test]
fn tc_line260_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/sm2_cert/ca.mul.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse sm2_ca.noCRL cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 263, X.509 cert parse KAT)
#[test]
fn tc_line263_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/sm2_cert/ca.noCRL.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse sm2_ca.notCA cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 266, X.509 cert parse KAT)
#[test]
fn tc_line266_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/sm2_cert/ca.notCA.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse sm2_enc cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 269, X.509 cert parse KAT)
#[test]
fn tc_line269_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/sm2_cert/enc.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse sm2_enc.mul cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 272, X.509 cert parse KAT)
#[test]
fn tc_line272_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/sm2_cert/enc.mul.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse sm2_enc.noCRL cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 275, X.509 cert parse KAT)
#[test]
fn tc_line275_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/sm2_cert/enc.noCRL.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse sm2_enc.notCA cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 278, X.509 cert parse KAT)
#[test]
fn tc_line278_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/sm2_cert/enc.notCA.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse sm2_enc2.mul cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 281, X.509 cert parse KAT)
#[test]
fn tc_line281_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/sm2_cert/enc2.mul.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse sm2_enc3.mul cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 284, X.509 cert parse KAT)
#[test]
fn tc_line284_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/sm2_cert/enc3.mul.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse sm2_sign cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 287, X.509 cert parse KAT)
#[test]
fn tc_line287_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/sm2_cert/sign.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse sm2_sign.mul cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 290, X.509 cert parse KAT)
#[test]
fn tc_line290_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/sm2_cert/sign.mul.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse sm2_sign.noCRL cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 293, X.509 cert parse KAT)
#[test]
fn tc_line293_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/sm2_cert/sign.noCRL.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse sm2_sign.notCA cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 296, X.509 cert parse KAT)
#[test]
fn tc_line296_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/sm2_cert/sign.notCA.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse sm2_sign2.mul cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 299, X.509 cert parse KAT)
#[test]
fn tc_line299_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/sm2_cert/sign2.mul.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse sm2_sign3.mul cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 302, X.509 cert parse KAT)
#[test]
fn tc_line302_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/sm2_cert/sign3.mul.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse sm2_inter cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 305, X.509 cert parse KAT)
#[test]
fn tc_line305_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/sm2_cert/inter.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse sm2_inter.mul cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 308, X.509 cert parse KAT)
#[test]
fn tc_line308_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/sm2_cert/inter.mul.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse sm2_inter.noCRL cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 311, X.509 cert parse KAT)
#[test]
fn tc_line311_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/sm2_cert/inter.noCRL.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse sm2_inter.notCA cert
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 314, X.509 cert parse KAT)
#[test]
fn tc_line314_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/sm2_cert/inter.notCA.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse ml-kem cert pem
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 317, X.509 cert parse KAT)
#[test]
fn tc_line317_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/mlkem_keys/mlkem512/mlkem512_cert.pem"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(Certificate::from_pem(pem).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse ml-kem cert pem
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 320, X.509 cert parse KAT)
#[test]
fn tc_line320_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/mlkem_keys/mlkem768/mlkem768_cert.pem"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(Certificate::from_pem(pem).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse ml-kem cert pem
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 323, X.509 cert parse KAT)
#[test]
fn tc_line323_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/mlkem_keys/mlkem1024/mlkem1024_cert.pem"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(Certificate::from_pem(pem).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse slh-dsa cert pem
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 326, X.509 cert parse KAT)
#[test]
fn tc_line326_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/slhdsa_keys/slhdsa_sha2_128s_cert.pem"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(Certificate::from_pem(pem).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse slh-dsa-sha2-128s CA cert PEM
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 329, X.509 cert parse KAT)
#[test]
fn tc_line329_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/slhdsa_cert/sha2_128s/ca.pem"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(Certificate::from_pem(pem).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse slh-dsa-sha2-128s CA cert DER
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 331, X.509 cert parse KAT)
#[test]
fn tc_line331_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/slhdsa_cert/sha2_128s/ca.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse slh-dsa-sha2-256f CA cert PEM
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 333, X.509 cert parse KAT)
#[test]
fn tc_line333_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/slhdsa_cert/sha2_256f/ca.pem"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(Certificate::from_pem(pem).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse slh-dsa-sha2-256f CA cert DER
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 335, X.509 cert parse KAT)
#[test]
fn tc_line335_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/slhdsa_cert/sha2_256f/ca.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse slh-dsa-shake-128s CA cert PEM
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 337, X.509 cert parse KAT)
#[test]
fn tc_line337_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/slhdsa_cert/shake_128s/ca.pem"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(Certificate::from_pem(pem).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse slh-dsa-shake-128s CA cert DER
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 339, X.509 cert parse KAT)
#[test]
fn tc_line339_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/slhdsa_cert/shake_128s/ca.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse slh-dsa-shake-256f CA cert PEM
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 341, X.509 cert parse KAT)
#[test]
fn tc_line341_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/slhdsa_cert/shake_256f/ca.pem"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(Certificate::from_pem(pem).is_ok());
}

/// SDV_X509_CERT_PARSE_FUNC_TC001 parse slh-dsa-shake-256f CA cert DER
/// C source: SDV_X509_CERT_PARSE_FUNC_TC001 (line 343, X.509 cert parse KAT)
#[test]
fn tc_line343_x509_cert_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/slhdsa_cert/shake_256f/ca.der"
    ))
    .unwrap();
    assert!(Certificate::from_der(&bytes).is_ok());
}

/// SDV_X509_CSR_PARSE_FUNC_TC001 #ed25519 csr without attribute
/// C source: SDV_X509_CSR_PARSE_FUNC_TC001 (line 14, X.509 csr parse KAT)
#[test]
fn tc_line14_x509_csr_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/ed25519/ed25519.ca.csr.pem"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(CertificateRequest::from_pem(pem).is_ok());
}

/// SDV_X509_CSR_PARSE_FUNC_TC001 #rsa sha256 csr without attribute
/// C source: SDV_X509_CSR_PARSE_FUNC_TC001 (line 17, X.509 csr parse KAT)
#[test]
fn tc_line17_x509_csr_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/pem/csr/csr.pem"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(CertificateRequest::from_pem(pem).is_ok());
}

/// SDV_X509_CSR_PARSE_FUNC_TC001 #ecdsa sha256 csr pem without attribute
/// C source: SDV_X509_CSR_PARSE_FUNC_TC001 (line 20, X.509 csr parse KAT)
#[test]
fn tc_line20_x509_csr_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/pem/csr/ecdsa_sha/ec_app256SHA256.csr"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(CertificateRequest::from_pem(pem).is_ok());
}

/// SDV_X509_CSR_PARSE_FUNC_TC001 #ecdsa sha256 csr asn1 without attribute
/// C source: SDV_X509_CSR_PARSE_FUNC_TC001 (line 23, X.509 csr parse KAT)
#[test]
fn tc_line23_x509_csr_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/asn1/ecdsa_sha_csr/ec_app256SHA256.csr.der"
    ))
    .unwrap();
    assert!(CertificateRequest::from_der(&bytes).is_ok());
}

/// SDV_X509_CSR_PARSE_FUNC_TC001 #rsa sha256 csr pem with attribute
/// C source: SDV_X509_CSR_PARSE_FUNC_TC001 (line 26, X.509 csr parse KAT)
#[test]
fn tc_line26_x509_csr_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/pem/csr/rsa_pss_sha/rsa2048_pss_withattr.csr"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(CertificateRequest::from_pem(pem).is_ok());
}

/// SDV_X509_CSR_PARSE_FUNC_TC001 #sm2 csr pem with userid
/// C source: SDV_X509_CSR_PARSE_FUNC_TC001 (line 29, X.509 csr parse KAT)
#[test]
fn tc_line29_x509_csr_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/pem/csr/sm2_with_userid/ca.csr"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(CertificateRequest::from_pem(pem).is_ok());
}

/// SDV_X509_CSR_PARSE_FUNC_TC001 #sm2 csr pem without userid
/// C source: SDV_X509_CSR_PARSE_FUNC_TC001 (line 32, X.509 csr parse KAT)
#[test]
fn tc_line32_x509_csr_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/pem/csr/sm2/ca.csr"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(CertificateRequest::from_pem(pem).is_ok());
}

/// SDV_X509_CSR_PARSE_FUNC_TC001 #mldsa_44
/// C source: SDV_X509_CSR_PARSE_FUNC_TC001 (line 35, X.509 csr parse KAT)
#[test]
fn tc_line35_x509_csr_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/pem/csr/mldsa/mldsa44.csr"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(CertificateRequest::from_pem(pem).is_ok());
}

/// SDV_X509_CSR_PARSE_FUNC_TC001 #mldsa65
/// C source: SDV_X509_CSR_PARSE_FUNC_TC001 (line 38, X.509 csr parse KAT)
#[test]
fn tc_line38_x509_csr_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/pem/csr/mldsa/mldsa65.csr"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(CertificateRequest::from_pem(pem).is_ok());
}

/// SDV_X509_CSR_PARSE_FUNC_TC001 #mldsa87 csr
/// C source: SDV_X509_CSR_PARSE_FUNC_TC001 (line 41, X.509 csr parse KAT)
#[test]
fn tc_line41_x509_csr_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/pem/csr/mldsa/mldsa87.csr"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(CertificateRequest::from_pem(pem).is_ok());
}

/// SDV_X509_CSR_PARSE_FUNC_TC001 #rsa_md5
/// C source: SDV_X509_CSR_PARSE_FUNC_TC001 (line 44, X.509 csr parse KAT)
#[test]
fn tc_line44_x509_csr_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/pem/csr/rsa_sha/rsa1024_pkcs8_md5.csr"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(CertificateRequest::from_pem(pem).is_ok());
}

/// SDV_X509_CSR_PARSE_FUNC_TC001 #rsa_sha1
/// C source: SDV_X509_CSR_PARSE_FUNC_TC001 (line 47, X.509 csr parse KAT)
#[test]
fn tc_line47_x509_csr_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/pem/csr/rsa_sha/rsa1024_pkcs8_sha1.csr"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(CertificateRequest::from_pem(pem).is_ok());
}

/// SDV_X509_CSR_PARSE_FUNC_TC001 #rsa_sha224
/// C source: SDV_X509_CSR_PARSE_FUNC_TC001 (line 50, X.509 csr parse KAT)
#[test]
fn tc_line50_x509_csr_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/pem/csr/rsa_sha/rsa1024_pkcs8_sha224.csr"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(CertificateRequest::from_pem(pem).is_ok());
}

/// SDV_X509_CSR_PARSE_FUNC_TC001 #rsa_sha384
/// C source: SDV_X509_CSR_PARSE_FUNC_TC001 (line 53, X.509 csr parse KAT)
#[test]
fn tc_line53_x509_csr_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/pem/csr/rsa_sha/rsa1024_pkcs8_sha384.csr"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(CertificateRequest::from_pem(pem).is_ok());
}

/// SDV_X509_CSR_PARSE_FUNC_TC001 #rsa_sha512
/// C source: SDV_X509_CSR_PARSE_FUNC_TC001 (line 56, X.509 csr parse KAT)
#[test]
fn tc_line56_x509_csr_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/pem/csr/rsa_sha/rsa1024_pkcs8_sha512.csr"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(CertificateRequest::from_pem(pem).is_ok());
}

/// C source: SDV_X509_CSR_PARSE_FUNC_TC002 (line 59, X.509 csr parse KAT)
#[test]
fn tc_line59_x509_csr_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/pem/csr/csr.pem"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(CertificateRequest::from_pem(pem).is_ok());
}

/// C source: SDV_X509_CSR_PARSE_FUNC_TC002 (line 62, X.509 csr parse KAT)
#[test]
fn tc_line62_x509_csr_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/pem/csr/dn/test_dn.pem"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(CertificateRequest::from_pem(pem).is_ok());
}

/// C source: SDV_X509_CSR_PARSE_FUNC_TC002 (line 65, X.509 csr parse KAT)
#[test]
fn tc_line65_x509_csr_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/pem/csr/dn/test_dn2.pem"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(CertificateRequest::from_pem(pem).is_ok());
}

/// C source: SDV_X509_CSR_PARSE_FUNC_TC003 (line 68, X.509 csr parse KAT)
#[test]
fn tc_line68_x509_csr_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/pem/csr/csr.pem"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(CertificateRequest::from_pem(pem).is_ok());
}

/// SDV_X509_CSR_PARSE_FUNC_TC003 #rsa sha256 csr asn1 with attribute
/// C source: SDV_X509_CSR_PARSE_FUNC_TC003 (line 71, X.509 csr parse KAT)
#[test]
fn tc_line71_x509_csr_parse() {
    let bytes = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/c-asn1-fixtures/cert/pem/csr/rsa_pss_sha/rsa2048_pss_withattr.csr"
    ))
    .unwrap();
    let pem = std::str::from_utf8(&bytes).unwrap();
    assert!(CertificateRequest::from_pem(pem).is_ok());
}

// Generation summary: 131 emitted / 1131 API-surface skipped / 8 unknown / 0 unsupported alg / 1270 total C cases.
