//! x509_crl.c non-RFC5280 negative-parse + extension round-trip tests
//! — T206 / #42.
//!
//! Phase C-3 of the PKI malformed-fixture migration plan
//! (`docs/issue-42-phase-c-plan.md`). Mirrors the non-RFC5280
//! portion of `openhitls/testcode/sdv/testcase/pki/crl/test_suite_sdv_x509_crl.c`
//! (45 fn / 448 rows): version / time / signature-algorithm / revoked-list /
//! extensions / issuer-name / multi-CRL parsing.
//!
//! The RFC 5280 strict-compliance subset is covered by
//! `migrated_crl_rfc5280_verify.rs` (T187 + T202, 32 tests) and
//! `migrated_crl_rfc5280_gap.rs` (9 tests). This file targets the
//! complementary attack surface: parser behaviour on the file-fixture
//! variants generated by the openHiTLS C harness — across signer
//! algorithms (RSA / ECDSA / DSA / SM2), version (v1 vs v2), and
//! revoked-list shapes (empty / single / multi).
//!
//! ## C-source decision matrix
//!
//! | C TC family | Rust coverage | Decision |
//! |-------------|---------------|----------|
//! | `PARSE_VERSION_FUNC_TC001` (v1 vs v2) | none | **port** — `rsa_crl/crl_v1.der` + `crl_v2.der` |
//! | `PARSE_REVOKEDLIST_FUNC_TC001` (empty / multi) | none | **port** — `crl_v1.noCRL.der` + `crl_v1.mul.der` |
//! | `PARSE_SIGNALG_FUNC_TC001` (per algorithm) | none | **port** — ECDSA + DSA + SM2 variants |
//! | `PARSE_EXTENSIONS_FUNC_TC001` (IAN / AKI) | none | **port** — `extension_crl/test_crl_add_issuer_alternative_name.pem` + `test_crl.pem` |
//! | `PARSE_ISSUERNAME_FUNC_TC001` | covered by `migrated_crl_rfc5280_gap` `tc_line17_*` etc. | scope-cut |
//! | `PARSE_REVOKED_FUNC_TC001/003` (reason code) | covered by `migrated_crl_rfc5280_gap` `tc_line101_*` etc. | scope-cut |
//! | `PARSE_TIME_FUNC` / `START_TIME` / `END_TIME` | covered by T187 `expired_crl` / `not_yet_valid_crl` | scope-cut |
//! | `PARSE_SIGNATURE_FUNC_TC001` (tampered signature) | covered by T187 `tc_tc003_r4_*_tampered_signature_rejected` | scope-cut |
//! | `CTRL_FUNC_TC001`, `ENCODE_STUB_TC001` | internal API; no Rust equivalent | scope-cut |
//!
//! ## Plan-doc cross-coverage pin
//!
//! `audit_plan_docs_in_sync` reads `docs/issue-42-phase-c-plan.md` and
//! asserts the key audit anchors stay locked, same pattern as T204/T205.

#![cfg(feature = "x509")]

use hitls_pki::x509::CertificateRevocationList;

/// Load a CRL fixture from `tests/vectors/c-asn1-fixtures/`.
fn load_crl(rel: &str) -> CertificateRevocationList {
    let path = format!(
        "{}/../../tests/vectors/c-asn1-fixtures/{}",
        env!("CARGO_MANIFEST_DIR"),
        rel
    );
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("missing fixture {path}: {e}"));
    match std::str::from_utf8(&bytes) {
        Ok(s) if s.contains("-----BEGIN") => CertificateRevocationList::from_pem(s).unwrap(),
        _ => CertificateRevocationList::from_der(&bytes).unwrap(),
    }
}

// ===========================================================================
// PARSE_VERSION_FUNC_TC001 — v1 vs v2 round-trip.
// ===========================================================================

/// Mirrors C `SDV_X509_CRL_PARSE_VERSION_FUNC_TC001` v1 row: the
/// `crl_v1.der` fixture parses with `version == 1` (RFC 5280 §5.1.1:
/// version absent = v1).
#[test]
fn crl_parse_rsa_v1_no_extensions() {
    let crl = load_crl("cert/asn1/rsa_crl/crl_v1.der");
    assert_eq!(crl.version, 1, "rsa_crl/crl_v1 must surface as version 1");
}

/// Mirrors C `SDV_X509_CRL_PARSE_VERSION_FUNC_TC001` v2 row: the
/// `crl_v2.der` fixture parses with `version == 2`. The fixture
/// carries at least one CRL-level extension (CRLNumber or AKI), which
/// is what bumps the version to 2.
#[test]
fn crl_parse_rsa_v2_with_extensions() {
    let crl = load_crl("cert/asn1/rsa_crl/crl_v2.der");
    assert_eq!(crl.version, 2, "rsa_crl/crl_v2 must surface as version 2");
}

// ===========================================================================
// PARSE_REVOKEDLIST_FUNC_TC001 — empty vs multi revoked list.
// ===========================================================================

/// Mirrors C `SDV_X509_CRL_PARSE_REVOKEDLIST_FUNC_TC001` empty-list row:
/// the `crl_v1.noCRL.der` fixture has no revoked entries. The parser
/// must surface a CRL whose `revoked_certs` is empty (or whatever the
/// no-list accessor returns).
#[test]
fn crl_parse_rsa_v1_empty_revoked_list() {
    let crl = load_crl("cert/asn1/rsa_crl/crl_v1.noCRL.der");
    // Pin that the parse succeeded and the version is 1 (the noCRL
    // variant is a v1 CRL by C convention).
    assert_eq!(crl.version, 1);
}

/// Mirrors C `SDV_X509_CRL_PARSE_REVOKEDLIST_FUNC_TC001` multi-entry
/// row: the `crl_v1.mul.der` fixture has multiple revoked entries.
/// Pin that the CRL parses cleanly under the multi-entry codepath.
#[test]
fn crl_parse_rsa_v1_multi_revoked_entries() {
    let crl = load_crl("cert/asn1/rsa_crl/crl_v1.mul.der");
    assert_eq!(crl.version, 1);
}

// ===========================================================================
// PARSE_SIGNALG_FUNC_TC001 — per-algorithm signature-algorithm rows.
// ===========================================================================

/// Mirrors C `SDV_X509_CRL_PARSE_SIGNALG_FUNC_TC001` ECDSA row:
/// the `ecdsa_crl/crl_v2.der` fixture parses without error.
#[test]
fn crl_parse_ecdsa_v2_signature_algorithm() {
    let crl = load_crl("cert/asn1/ecdsa_crl/crl_v2.der");
    assert_eq!(crl.version, 2);
}

/// DSA row — Rust's CRL parser currently rejects DSA-SHA-256 CRLs
/// (`InvalidCrl("unknown TBS signature algorithm: 2.16.840.1.101.3.4.3.2")`).
/// Pin the gap so a future signature-algorithm extension lands as a
/// deliberate change (DSA was deprecated by FIPS 186-5 but legacy
/// fixtures persist).
#[test]
fn crl_parse_dsa_v2_signature_algorithm_unsupported_gap() {
    let path = format!(
        "{}/../../tests/vectors/c-asn1-fixtures/cert/asn1/dsa_crl/crl_v2.der",
        env!("CARGO_MANIFEST_DIR")
    );
    let bytes = std::fs::read(&path).unwrap();
    let err = CertificateRevocationList::from_der(&bytes)
        .expect_err("DSA-SHA-256 CRL must currently fail to parse");
    let msg = format!("{err:?}");
    assert!(
        msg.contains("2.16.840.1.101.3.4.3.2") || msg.to_ascii_lowercase().contains("unknown"),
        "DSA-SHA-256 reject should mention the unsupported OID or 'unknown'; got: {msg}"
    );
    // TODO(#42-phase-c): add DSA-SHA-256 to the CRL signature-algorithm
    // dispatch table if DSA verification ever becomes a target.
}

/// SM2 row — Chinese cryptographic algorithm; mirrors the GM/T 0009
/// CRL profile.
#[test]
fn crl_parse_sm2_v2_signature_algorithm() {
    let crl = load_crl("cert/asn1/sm2_crl/crl_v2.der");
    assert_eq!(crl.version, 2);
}

// ===========================================================================
// PARSE_EXTENSIONS_FUNC_TC001 — IssuerAltName / AKI extension rows.
// ===========================================================================

/// Mirrors C `SDV_X509_CRL_PARSE_EXTENSIONS_FUNC_TC001` IssuerAltName
/// row: the `test_crl_add_issuer_alternative_name.pem` fixture carries
/// an IssuerAlternativeName extension on the CRL. Pin that the parser
/// tolerates it (Rust does not require IAN-specific accessor surface;
/// this is a parse-doesn't-reject pin).
#[test]
fn crl_parse_extension_issuer_alternative_name_tolerated() {
    let crl = load_crl("cert/test_for_crl/extension_crl/test_crl_add_issuer_alternative_name.pem");
    assert_eq!(crl.version, 2);
}

/// Mirrors C `SDV_X509_CRL_PARSE_EXTENSIONS_FUNC_TC001` baseline row:
/// `test_crl.pem` is the plain extension-carrying CRL the
/// `extension_crl/` fixtures derive from.
#[test]
fn crl_parse_extension_baseline_test_crl() {
    let crl = load_crl("cert/test_for_crl/extension_crl/test_crl.pem");
    assert_eq!(crl.version, 2);
    // The baseline carries a CRLNumber; pin its presence.
    assert!(
        crl.crl_number().is_some(),
        "baseline test_crl.pem must carry a CRLNumber extension"
    );
}

// ===========================================================================
// Plan-doc cross-coverage pin.
// ===========================================================================

/// Reads `docs/issue-42-phase-c-plan.md` and asserts key audit
/// anchors stay locked. Same pattern as T204/T205.
#[test]
fn audit_plan_docs_in_sync() {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let plan_path = format!("{manifest_dir}/../../docs/issue-42-phase-c-plan.md");
    let plan = std::fs::read_to_string(&plan_path)
        .unwrap_or_else(|e| panic!("missing audit doc at {plan_path}: {e}"));

    for tag in &[
        "T204", "T205", "T206", "T207", "T208", "C-1", "C-2", "C-3", "C-4",
    ] {
        assert!(plan.contains(tag), "plan doc missing sub-PR tag `{tag}`");
    }

    for anchor in &["x509_crl.c", "TODO(#42-phase-c)"] {
        assert!(
            plan.contains(anchor),
            "plan doc must keep anchor `{anchor}`"
        );
    }
}
