// This file is GENERATED by `cargo xtask migrate-c-tests --algo sm9`.
// DO NOT EDIT BY HAND. Source: openhitls C SDV
// test_suite_sdv_eal_sm9_sign.data + ..._crypt.data + ..._exchange.data
//
// Generator: docs/c-test-migration-plan.md Phase A (xtask).
#![cfg(all(feature = "sm9", feature = "kat-nonce"))]

use hitls_crypto::sm9::{Sm9KeyType, Sm9MasterKey};

/// C source: SDV_CRYPTO_SM9_SIGN_API_TC001 (line 4, SM9 sign+verify round-trip)
#[test]
#[allow(deprecated)]
fn tc_line4_sm9_sign_tc001() {
    let master_key: &[u8] = &[
        0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef, 0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd,
        0xef, 0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef, 0x01, 0x23, 0x45, 0x67, 0x89, 0xab,
        0xcd, 0xef,
    ];
    let user_id: &[u8] = &[0x41, 0x6c, 0x69, 0x63, 0x65];
    let msg: &[u8] = &[0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x20, 0x53, 0x4d, 0x39, 0x21];
    let master = Sm9MasterKey::from_master_secret(Sm9KeyType::Sign, master_key).unwrap();
    let user = master.extract_user_key(user_id).unwrap();
    let sig = user.sign(msg, master.master_public_key()).unwrap();
    assert!(
        master.verify(user_id, msg, &sig).unwrap(),
        "valid signature must verify"
    );
    let wrong_msg = b"Wrong Message";
    assert!(
        !master.verify(user_id, wrong_msg, &sig).unwrap(),
        "wrong-message verify must fail"
    );
}

/// C source: SDV_CRYPTO_SM9_SIGN_API_TC002 (line 7, SM9 sign+verify round-trip)
#[test]
#[allow(deprecated)]
fn tc_line7_sm9_sign_tc002() {
    let master_key: &[u8] = &[
        0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef, 0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd,
        0xef, 0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef, 0x01, 0x23, 0x45, 0x67, 0x89, 0xab,
        0xcd, 0xef,
    ];
    let user_id: &[u8] = &[0x41, 0x6c, 0x69, 0x63, 0x65];
    let msg: &[u8] = &[
        0x54, 0x65, 0x73, 0x74, 0x20, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
    ];
    let master = Sm9MasterKey::from_master_secret(Sm9KeyType::Sign, master_key).unwrap();
    let user = master.extract_user_key(user_id).unwrap();
    let sig = user.sign(msg, master.master_public_key()).unwrap();
    assert!(
        master.verify(user_id, msg, &sig).unwrap(),
        "valid signature must verify"
    );
    let wrong_msg = b"Wrong Message";
    assert!(
        !master.verify(user_id, wrong_msg, &sig).unwrap(),
        "wrong-message verify must fail"
    );
}

/// C source: SDV_CRYPTO_SM9_CHECK_KEYPAIR_FUNC_TC001 (line 40, SM9 check-keypair (dual-user extract round-trip))
#[test]
#[allow(deprecated)]
fn tc_line40_sm9_check_keypair() {
    let master_key: &[u8] = &[
        0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef, 0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd,
        0xef, 0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef, 0x01, 0x23, 0x45, 0x67, 0x89, 0xab,
        0xcd, 0xef,
    ];
    let user_id1: &[u8] = &[0x41, 0x6c, 0x69, 0x63, 0x65];
    let user_id2: &[u8] = &[0x42, 0x6f, 0x62];
    let master = Sm9MasterKey::from_master_secret(Sm9KeyType::Sign, master_key).unwrap();
    let user1 = master.extract_user_key(user_id1).unwrap();
    let user2 = master.extract_user_key(user_id2).unwrap();
    let msg = b"keypair check";
    let sig1 = user1.sign(msg, master.master_public_key()).unwrap();
    let sig2 = user2.sign(msg, master.master_public_key()).unwrap();
    assert!(master.verify(user_id1, msg, &sig1).unwrap());
    assert!(master.verify(user_id2, msg, &sig2).unwrap());
    assert!(
        !master.verify(user_id2, msg, &sig1).unwrap(),
        "cross-identity verify must fail"
    );
}

/// C source: SDV_CRYPTO_SM9_CHECK_PRVKEY_FUNC_TC001 (line 43, SM9 check-prvkey (derive + sign round-trip))
#[test]
#[allow(deprecated)]
fn tc_line43_sm9_check_prvkey() {
    let master_key: &[u8] = &[
        0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef, 0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd,
        0xef, 0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef, 0x01, 0x23, 0x45, 0x67, 0x89, 0xab,
        0xcd, 0xef,
    ];
    let user_id: &[u8] = &[0x41, 0x6c, 0x69, 0x63, 0x65];
    let master = Sm9MasterKey::from_master_secret(Sm9KeyType::Sign, master_key).unwrap();
    let user = master.extract_user_key(user_id).unwrap();
    let msg = b"prvkey check";
    let sig = user.sign(msg, master.master_public_key()).unwrap();
    assert!(
        master.verify(user_id, msg, &sig).unwrap(),
        "derived private key must produce a valid signature"
    );
}

/// C source: SDV_CRYPTO_SM9_CRYPT_API_TC001 (line 4, SM9 encrypt+decrypt round-trip (same user))
#[test]
#[allow(deprecated)]
fn tc_line4_sm9_crypt_self_tc001() {
    let master_key: &[u8] = &[
        0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54, 0x32, 0x10, 0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54, 0x32,
        0x10, 0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54, 0x32, 0x10, 0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54,
        0x32, 0x10,
    ];
    let user_id: &[u8] = &[0x41, 0x6c, 0x69, 0x63, 0x65];
    let pt: &[u8] = &[
        0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x20, 0x40, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
    ];
    let master = Sm9MasterKey::from_master_secret(Sm9KeyType::Encrypt, master_key).unwrap();
    let user = master.extract_user_key(user_id).unwrap();
    let ct = master.encrypt(user_id, pt).unwrap();
    let decrypted = user.decrypt(&ct).unwrap();
    assert_eq!(decrypted.as_slice(), pt);
}

/// C source: SDV_CRYPTO_SM9_CRYPT_API_TC002 (line 7, SM9 encrypt+decrypt round-trip (same user))
#[test]
#[allow(deprecated)]
fn tc_line7_sm9_crypt_self_tc002() {
    let master_key: &[u8] = &[
        0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54, 0x32, 0x10, 0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54, 0x32,
        0x10, 0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54, 0x32, 0x10, 0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54,
        0x32, 0x10,
    ];
    let user_id: &[u8] = &[0x41, 0x6c, 0x69, 0x63, 0x65];
    let pt: &[u8] = &[
        0x54, 0x65, 0x73, 0x74, 0x02, 0x0c, 0x6c, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x78, 0x74,
    ];
    let master = Sm9MasterKey::from_master_secret(Sm9KeyType::Encrypt, master_key).unwrap();
    let user = master.extract_user_key(user_id).unwrap();
    let ct = master.encrypt(user_id, pt).unwrap();
    let decrypted = user.decrypt(&ct).unwrap();
    assert_eq!(decrypted.as_slice(), pt);
}

/// C source: SDV_CRYPTO_SM9_CRYPT_API_TC003 (line 10, SM9 encrypt+decrypt round-trip (cross-user))
#[test]
#[allow(deprecated)]
fn tc_line10_sm9_crypt_cross() {
    let master_key: &[u8] = &[
        0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54, 0x32, 0x10, 0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54, 0x32,
        0x10, 0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54, 0x32, 0x10, 0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54,
        0x32, 0x10,
    ];
    let user_a: &[u8] = &[0x41, 0x6c, 0x69, 0x63, 0x65];
    let user_b: &[u8] = &[0x42, 0x6f, 0x62];
    let pt: &[u8] = &[
        0x43, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x20, 0x44, 0x61,
        0x74, 0x61,
    ];
    let master = Sm9MasterKey::from_master_secret(Sm9KeyType::Encrypt, master_key).unwrap();
    let user_a_key = master.extract_user_key(user_a).unwrap();
    let user_b_key = master.extract_user_key(user_b).unwrap();
    let ct = master.encrypt(user_b, pt).unwrap();
    let decrypted_b = user_b_key.decrypt(&ct).unwrap();
    assert_eq!(decrypted_b.as_slice(), pt);
    assert!(
        user_a_key.decrypt(&ct).is_err(),
        "user A must not decrypt ciphertext addressed to user B"
    );
}

// Generation summary: 7 emitted / 31 API-surface skipped (N/A in Rust) / 0 unknown / 0 unsupported alg / 38 total C cases.
