// This file is GENERATED by `cargo xtask migrate-c-tests --algo drbg`.
// DO NOT EDIT BY HAND. Source: openhitls C SDV test_suite_sdv_drbg.data
//
// Generator: docs/c-test-migration-plan.md Phase A (xtask).

#![cfg(feature = "drbg")]

use hitls_crypto::drbg::hash_drbg::HashDrbgType;
use hitls_crypto::drbg::CtrDrbg;
use hitls_crypto::drbg::HashDrbg;
use hitls_crypto::drbg::HmacDrbg;

/// Personalization string fixed by the C SDV harness.
const PERS: [u8; 6] = [0x00, 0x01, 0x02, 0x03, 0x04, 0x05];

/// SDV_PRIMARY_DRBG_VECTOR_FUN_TC001 sah256
/// C source: SDV_PRIMARY_DRBG_VECTOR_FUN_TC001 (line 613, DRBG NIST vector: instantiate(0xff entropy/nonce, pers=00..05) + generate(32))
#[test]
fn tc_line613_bsl_cid_rand_sha256_vector() {
    let expected: &[u8] = &[
        0x93, 0x90, 0x71, 0x65, 0x85, 0x67, 0xfc, 0x48, 0xe3, 0xc9, 0xd4, 0x90, 0x72, 0x62, 0x54,
        0xe1, 0x08, 0xcb, 0x5a, 0x62, 0xcd, 0x54, 0x9e, 0x8f, 0x0c, 0xc1, 0xd1, 0xf0, 0x61, 0xe7,
        0x7e, 0xcd,
    ];
    let mut seed = vec![0xffu8; 1000 + 20];
    seed.extend_from_slice(&PERS);
    let mut d = HashDrbg::new(HashDrbgType::Sha256, &seed).unwrap();
    let mut got = [0u8; 32];
    d.generate(&mut got, None).unwrap();
    assert_eq!(&got[..], expected);
}

/// SDV_PRIMARY_DRBG_VECTOR_FUN_TC001 sha384
/// C source: SDV_PRIMARY_DRBG_VECTOR_FUN_TC001 (line 616, DRBG NIST vector: instantiate(0xff entropy/nonce, pers=00..05) + generate(32))
#[test]
fn tc_line616_bsl_cid_rand_sha384_vector() {
    let expected: &[u8] = &[
        0x93, 0x21, 0xbe, 0x06, 0x54, 0x01, 0x60, 0x49, 0x0f, 0x11, 0x04, 0x7f, 0x98, 0x1c, 0xe1,
        0xca, 0x7f, 0x92, 0xb6, 0x52, 0x27, 0x2a, 0xbe, 0xe2, 0x72, 0xdd, 0x0e, 0xd0, 0xa3, 0x53,
        0xd0, 0x4d,
    ];
    let mut seed = vec![0xffu8; 1000 + 20];
    seed.extend_from_slice(&PERS);
    let mut d = HashDrbg::new(HashDrbgType::Sha384, &seed).unwrap();
    let mut got = [0u8; 32];
    d.generate(&mut got, None).unwrap();
    assert_eq!(&got[..], expected);
}

/// SDV_PRIMARY_DRBG_VECTOR_FUN_TC001 sha512
/// C source: SDV_PRIMARY_DRBG_VECTOR_FUN_TC001 (line 619, DRBG NIST vector: instantiate(0xff entropy/nonce, pers=00..05) + generate(32))
#[test]
fn tc_line619_bsl_cid_rand_sha512_vector() {
    let expected: &[u8] = &[
        0x98, 0x0d, 0x64, 0x18, 0xe6, 0x11, 0xd7, 0x3e, 0x8d, 0x73, 0x39, 0x6a, 0xf7, 0xb2, 0x49,
        0x18, 0x78, 0x20, 0xb9, 0xdb, 0xb7, 0x7f, 0x78, 0x5a, 0xff, 0xd6, 0x74, 0x30, 0xa5, 0x01,
        0x86, 0x78,
    ];
    let mut seed = vec![0xffu8; 1000 + 20];
    seed.extend_from_slice(&PERS);
    let mut d = HashDrbg::new(HashDrbgType::Sha512, &seed).unwrap();
    let mut got = [0u8; 32];
    d.generate(&mut got, None).unwrap();
    assert_eq!(&got[..], expected);
}

/// SDV_PRIMARY_DRBG_VECTOR_FUN_TC001 hmac-sha256
/// C source: SDV_PRIMARY_DRBG_VECTOR_FUN_TC001 (line 628, DRBG NIST vector: instantiate(0xff entropy/nonce, pers=00..05) + generate(32))
#[test]
fn tc_line628_bsl_cid_rand_hmac_sha256_vector() {
    let expected: &[u8] = &[
        0x62, 0x0c, 0xb4, 0x19, 0x51, 0x2f, 0x9a, 0xdb, 0xab, 0x5c, 0xcc, 0x14, 0x6f, 0x5e, 0x2d,
        0x86, 0x79, 0xb6, 0x18, 0x47, 0x80, 0x46, 0x68, 0x6f, 0x2f, 0x4c, 0x3a, 0xfc, 0x0f, 0x5f,
        0xa1, 0x6e,
    ];
    let mut seed = vec![0xffu8; 1000 + 20];
    seed.extend_from_slice(&PERS);
    let mut d = HmacDrbg::new(&seed).unwrap();
    let mut got = [0u8; 32];
    d.generate(&mut got, None).unwrap();
    assert_eq!(&got[..], expected);
}

/// SDV_PRIMARY_DRBG_VECTOR_FUN_TC001 aes256-ctr
/// C source: SDV_PRIMARY_DRBG_VECTOR_FUN_TC001 (line 643, DRBG NIST vector: instantiate(0xff entropy/nonce, pers=00..05) + generate(32))
#[test]
fn tc_line643_bsl_cid_rand_aes256_ctr_vector() {
    let expected: &[u8] = &[
        0xe0, 0x48, 0xd5, 0x01, 0xd7, 0x47, 0x87, 0x89, 0xa9, 0x81, 0x5e, 0xf9, 0x4d, 0xbc, 0xd6,
        0x32, 0x49, 0x29, 0x90, 0x49, 0x05, 0xf5, 0x76, 0xcd, 0xaa, 0x0b, 0x2d, 0xc8, 0x5a, 0xa8,
        0x6f, 0xdd,
    ];
    let mut seed = vec![0xffu8; 48];
    for (i, p) in PERS.iter().enumerate() {
        seed[i] ^= *p;
    }
    let mut d = CtrDrbg::new(&seed).unwrap();
    let mut got = [0u8; 32];
    d.generate(&mut got, None).unwrap();
    assert_eq!(&got[..], expected);
}

/// SDV_PRIMARY_DRBG_VECTOR_FUN_TC001 aes256-ctr-df
/// C source: SDV_PRIMARY_DRBG_VECTOR_FUN_TC001 (line 652, DRBG NIST vector: instantiate(0xff entropy/nonce, pers=00..05) + generate(32))
#[test]
fn tc_line652_bsl_cid_rand_aes256_ctr_df_vector() {
    let expected: &[u8] = &[
        0xa0, 0x1d, 0xb1, 0xcf, 0x47, 0x33, 0xac, 0xf9, 0xbf, 0x26, 0x84, 0x1d, 0x93, 0x45, 0xbf,
        0x32, 0xe0, 0x05, 0x6b, 0x9a, 0xd9, 0x27, 0x22, 0x92, 0x53, 0xe4, 0x15, 0xe6, 0xe9, 0x6b,
        0x2b, 0x94,
    ];
    let entropy = vec![0xffu8; 1000];
    let nonce = [0xffu8; 20];
    let mut d = CtrDrbg::with_df(&entropy, &nonce, &PERS).unwrap();
    let mut got = [0u8; 32];
    d.generate(&mut got, None).unwrap();
    assert_eq!(&got[..], expected);
}

// Generation summary: 6 emitted / 272 API-surface skipped / 0 unknown / 12 unsupported alg / 290 total C cases.
