use std::collections::BTreeSet;
use std::fmt::Write;

use crate::digest::EmitStats;
use crate::parser::{format_byte_slice, Arg, TestCase};

/// AES `.data` rows that carry a real one-shot KAT use the
/// `_FUNC_TC001` suffix and follow either of two row shapes:
///
/// * Shape A (with provider flag): `flag : alg : key : iv : input : output : bool` (7 args)
/// * Shape B (no flag): `alg : key : iv : input : output : bool` (6 args)
///
/// All other TC suffixes (TC002 MCT, TC003 reinit, TC004 padding, TC005-6
/// multi-update, TC007 overlap, TC008-9 padding-mode) are workflow tests
/// without a clean one-shot mapping to the Rust API. They are routed to
/// `ApiSurface` for now — future commits can lift specific ones into
/// dedicated emitters as the Rust API grows (e.g. a `cbc_encrypt_raw`
/// no-padding variant would unlock the CBC KAT rows).
pub fn emit_aes_kat(cases: &[TestCase]) -> (String, EmitStats) {
    let mut body = String::new();
    let mut stats = EmitStats::default();
    let mut used_modes: BTreeSet<&'static str> = BTreeSet::new();

    for case in cases {
        match classify_aes(&case.tc_name) {
            AesKind::OneShot => emit_one_shot(&mut body, case, &mut stats, &mut used_modes),
            AesKind::ApiSurface => stats.skipped_api += 1,
            AesKind::Unknown => stats.skipped_unknown += 1,
        }
    }

    let mut out = String::new();
    write_header(&mut out, &used_modes);
    out.push_str(&body);
    write_footer(&mut out, &stats, cases.len());
    (out, stats)
}

#[derive(Debug, Clone, Copy)]
enum AesKind {
    /// `_ENCRYPT_FUNC_TC001`: one-shot KAT with single-block plaintext.
    OneShot,
    /// Architectural / workflow patterns.
    ApiSurface,
    Unknown,
}

fn classify_aes(tc_name: &str) -> AesKind {
    // API / lifecycle / multi-thread / overlap probes — none of these
    // have a 1:1 mapping to Rust's stateless one-shot mode helpers.
    if tc_name.contains("_API_TC")
        || tc_name.contains("_INIT_API")
        || tc_name.contains("_REINIT_API")
        || tc_name.contains("_FINAL_API")
        || tc_name.contains("_DEINIT_API")
        || tc_name.contains("_UPDATE_API")
        || tc_name.contains("_NEW_CTX_API")
        || tc_name.contains("_CTRL_API")
        || tc_name.contains("_GET_PADDING_API")
        || tc_name.contains("_SET_PADDING_API")
        || tc_name.contains("_STATE_CHANGE_API")
        || tc_name.contains("_MULTI_THREAD_FUNC")
        || tc_name.contains("_OVERLAP_FUNC")
        || tc_name.contains("_XTS_GET_IV_TC")
    {
        return AesKind::ApiSurface;
    }
    if tc_name.contains("_ENCRYPT_FUNC_TC001") {
        AesKind::OneShot
    } else if tc_name.contains("_ENCRYPT_FUNC_TC") || tc_name.contains("_FUNC_TC") {
        // TC002 (MCT), TC003 (reinit), TC004/8/9 (padding modes), TC005-6
        // (multi-update), TC007 (overlap) — workflow tests, not clean
        // one-shot KATs. Skip for the AES pilot.
        AesKind::ApiSurface
    } else {
        AesKind::Unknown
    }
}

/// Map a `CRYPT_CIPHER_AESxxx_<MODE>` symbol to (Rust mode tag, key size).
/// Returns `None` for modes whose Rust API requires a no-padding variant
/// we don't yet expose (CBC) or for unsupported variants.
fn aes_alg_label(symbol: &str) -> Option<(&'static str, usize)> {
    match symbol {
        "CRYPT_CIPHER_AES128_ECB" => Some(("ecb", 128)),
        "CRYPT_CIPHER_AES192_ECB" => Some(("ecb", 192)),
        "CRYPT_CIPHER_AES256_ECB" => Some(("ecb", 256)),
        "CRYPT_CIPHER_AES128_CTR" => Some(("ctr", 128)),
        "CRYPT_CIPHER_AES192_CTR" => Some(("ctr", 192)),
        "CRYPT_CIPHER_AES256_CTR" => Some(("ctr", 256)),
        // CBC: cbc_encrypt/decrypt hardcode PKCS#7 padding; raw NIST KAT
        // vectors are block-aligned with no padding. Skipped until the
        // Rust port grows a `cbc_encrypt_raw` helper (future phase).
        "CRYPT_CIPHER_AES128_CBC" | "CRYPT_CIPHER_AES192_CBC" | "CRYPT_CIPHER_AES256_CBC" => None,
        // CFB / OFB: stream-style helpers exist (no padding) but the
        // TC001 rows are ECB+CBC+CTR only. CFB/OFB live in TC005/TC006
        // (multi-update) which are routed to ApiSurface above.
        _ => None,
    }
}

fn write_header(out: &mut String, used_modes: &BTreeSet<&'static str>) {
    out.push_str(
        "// This file is GENERATED by `cargo xtask migrate-c-tests --algo aes`.\n\
         // DO NOT EDIT BY HAND. Source: openhitls C SDV test_suite_sdv_eal_aes.data\n\
         //\n\
         // Generator: docs/c-test-migration-plan.md Phase A (xtask).\n\n",
    );
    out.push_str("#![cfg(all(feature = \"aes\", feature = \"modes\"))]\n\n");

    // Per-mode imports keep the generated file's `use` list precise.
    // BTreeSet iteration is sorted, so output is deterministic across
    // regen runs (matters for --check drift detection).
    let mut imports: Vec<&str> = Vec::new();
    for mode in used_modes {
        match *mode {
            "ecb" => imports.push("use hitls_crypto::modes::ecb::{ecb_decrypt, ecb_encrypt};"),
            "ctr" => imports.push("use hitls_crypto::modes::ctr::ctr_crypt;"),
            _ => {}
        }
    }
    for line in imports {
        writeln!(out, "{line}").unwrap();
    }
    if !used_modes.is_empty() {
        out.push('\n');
    }
}

fn write_footer(out: &mut String, stats: &EmitStats, total: usize) {
    writeln!(
        out,
        "\n// Generation summary: {emitted} emitted / {api} API-surface skipped (workflow / lifecycle / padded-CBC) \
         / {unk} unknown / {unsupported} unsupported alg / {total} total C cases.",
        emitted = stats.emitted,
        api = stats.skipped_api,
        unk = stats.skipped_unknown,
        unsupported = stats.skipped_unsupported_alg,
        total = total,
    )
    .unwrap();
}

fn emit_one_shot(
    out: &mut String,
    case: &TestCase,
    stats: &mut EmitStats,
    used_modes: &mut BTreeSet<&'static str>,
) {
    // Detect row shape by locating the `CRYPT_CIPHER_` symbol. With the
    // provider flag (Shape A) it sits at args[1]; without it (Shape B) at
    // args[0]. Everything after the symbol is `key, iv, input, output,
    // direction-bool`.
    let alg_idx = case
        .args
        .iter()
        .position(|a| matches!(a, Arg::Symbol(s) if s.starts_with("CRYPT_CIPHER_")));
    let Some(alg_idx) = alg_idx else {
        stats.skipped_unknown += 1;
        return;
    };
    // Expect exactly 5 args after the alg symbol: key, iv, input,
    // output, bool.
    if alg_idx + 5 >= case.args.len() {
        stats.skipped_unknown += 1;
        return;
    }
    let alg = match &case.args[alg_idx] {
        Arg::Symbol(s) => s.as_str(),
        _ => {
            stats.skipped_unknown += 1;
            return;
        }
    };
    let Some(key) = case.args[alg_idx + 1].as_hex() else {
        stats.skipped_unknown += 1;
        return;
    };
    let Some(iv) = case.args[alg_idx + 2].as_hex() else {
        stats.skipped_unknown += 1;
        return;
    };
    let Some(input) = case.args[alg_idx + 3].as_hex() else {
        stats.skipped_unknown += 1;
        return;
    };
    let Some(output) = case.args[alg_idx + 4].as_hex() else {
        stats.skipped_unknown += 1;
        return;
    };
    let dir_arg = match &case.args[alg_idx + 5] {
        Arg::Symbol(s) => s.as_str(),
        _ => {
            stats.skipped_unknown += 1;
            return;
        }
    };
    let encrypt = match dir_arg {
        "true" => true,
        "false" => false,
        _ => {
            stats.skipped_unknown += 1;
            return;
        }
    };

    let Some((mode_label, key_bits)) = aes_alg_label(alg) else {
        stats.skipped_unsupported_alg += 1;
        return;
    };

    // Mode-specific IV-shape sanity checks catch data-file
    // inconsistencies early.
    match mode_label {
        "ecb" if !iv.is_empty() => {
            stats.skipped_unknown += 1;
            return;
        }
        "ctr" if iv.is_empty() => {
            stats.skipped_unknown += 1;
            return;
        }
        _ => {}
    }
    used_modes.insert(mode_label);

    let dir_tag = if encrypt { "encrypt" } else { "decrypt" };
    let fn_name = format!(
        "tc_line{}_aes{}_{}_{}",
        case.line, key_bits, mode_label, dir_tag
    );

    write_test_doc(out, case);
    writeln!(out, "#[test]").unwrap();
    writeln!(out, "fn {fn_name}() {{").unwrap();
    writeln!(out, "    let key: &[u8] = {};", format_byte_slice(key)).unwrap();
    if mode_label != "ecb" {
        writeln!(out, "    let iv: &[u8] = {};", format_byte_slice(iv)).unwrap();
    }
    writeln!(out, "    let input: &[u8] = {};", format_byte_slice(input)).unwrap();
    writeln!(
        out,
        "    let expected: &[u8] = {};",
        format_byte_slice(output)
    )
    .unwrap();

    match (mode_label, encrypt) {
        ("ecb", true) => {
            writeln!(out, "    let actual = ecb_encrypt(key, input).unwrap();").unwrap();
            writeln!(out, "    assert_eq!(actual.as_slice(), expected);").unwrap();
        }
        ("ecb", false) => {
            writeln!(out, "    let actual = ecb_decrypt(key, input).unwrap();").unwrap();
            writeln!(out, "    assert_eq!(actual.as_slice(), expected);").unwrap();
        }
        ("ctr", _) => {
            // CTR is symmetric — same fn for encrypt and decrypt. The
            // `_dir` suffix on the test name preserves traceability
            // back to the C row (which is direction-aware).
            writeln!(out, "    let mut actual = input.to_vec();").unwrap();
            writeln!(out, "    ctr_crypt(key, iv, &mut actual).unwrap();").unwrap();
            writeln!(out, "    assert_eq!(actual.as_slice(), expected);").unwrap();
        }
        _ => unreachable!("emit_one_shot dispatched on an unsupported mode label"),
    }
    writeln!(out, "}}\n").unwrap();
    stats.emitted += 1;
}

fn write_test_doc(out: &mut String, case: &TestCase) {
    if let Some(desc) = &case.description {
        writeln!(out, "/// {desc}").unwrap();
    }
    writeln!(
        out,
        "/// C source: {} (line {}, one-shot AES KAT)",
        case.tc_name, case.line
    )
    .unwrap();
}
