use std::fmt::Write;

use crate::parser::{format_byte_slice, TestCase};

#[derive(Debug, Default)]
pub struct EmitStats {
    pub emitted: usize,
    pub skipped_api: usize,
    pub skipped_unknown: usize,
    pub skipped_unsupported_alg: usize,
}

pub fn emit_sha2_kat(cases: &[TestCase]) -> (String, EmitStats) {
    let mut out = String::new();
    let mut stats = EmitStats::default();

    write_header(&mut out);

    for case in cases {
        let kind = classify(&case.tc_name);
        match kind {
            CaseKind::OneShot => emit_one_shot(&mut out, case, &mut stats),
            CaseKind::EmptyInput => emit_empty_input(&mut out, case, &mut stats),
            CaseKind::MultiBlock => emit_multi_block(&mut out, case, &mut stats),
            CaseKind::ApiSurface => stats.skipped_api += 1,
            CaseKind::Unknown => stats.skipped_unknown += 1,
        }
    }

    write_footer(&mut out, &stats, cases.len());
    (out, stats)
}

#[derive(Debug, Clone, Copy)]
enum CaseKind {
    /// FUNC_TC003: alg + input + expected (one-shot digest KAT).
    OneShot,
    /// FUNC_TC002: alg + expected (init+final, no update — empty input).
    EmptyInput,
    /// FUNC_TC004: alg + 3 input parts + expected (multi-block split-update).
    MultiBlock,
    /// API_TC001/2/3 + FUNC_TC001/5: lifecycle / threading.
    ApiSurface,
    Unknown,
}

fn classify(tc_name: &str) -> CaseKind {
    // Architectural patterns / special-template families must be
    // checked FIRST: `_MB_` (multi-buffer 4-way SHA-256, needs its
    // own template), `_COPY_CTX_` (context-clone tests), and
    // `_DEFAULT_PROVIDER_` (provider abstraction — N/A in Rust)
    // all have substrings that would otherwise be mismatched by
    // the generic `_FUNC_TC0NN` rules below.
    if tc_name.contains("_MB_")
        || tc_name.contains("_COPY_CTX_")
        || tc_name.contains("_DEFAULT_PROVIDER_")
        || tc_name.contains("_API_TC")
        || tc_name.contains("_FUNC_TC001")
        || tc_name.contains("_FUNC_TC005")
    {
        return CaseKind::ApiSurface;
    }
    if tc_name.contains("_FUNC_TC003") {
        CaseKind::OneShot
    } else if tc_name.contains("_FUNC_TC002") {
        CaseKind::EmptyInput
    } else if tc_name.contains("_FUNC_TC004") {
        CaseKind::MultiBlock
    } else {
        CaseKind::Unknown
    }
}

fn alg_to_rust(symbol: &str) -> Option<&'static str> {
    match symbol {
        "CRYPT_MD_SHA224" => Some("Sha224"),
        "CRYPT_MD_SHA256" => Some("Sha256"),
        "CRYPT_MD_SHA384" => Some("Sha384"),
        "CRYPT_MD_SHA512" => Some("Sha512"),
        _ => None,
    }
}

fn alg_lower(rust_ty: &str) -> &'static str {
    match rust_ty {
        "Sha224" => "sha224",
        "Sha256" => "sha256",
        "Sha384" => "sha384",
        "Sha512" => "sha512",
        _ => "unknown",
    }
}

fn write_header(out: &mut String) {
    out.push_str(
        "// This file is GENERATED by `cargo xtask migrate-c-tests --algo sha2`.\n\
         // DO NOT EDIT BY HAND. Source: openhitls C SDV test_suite_sdv_eal_md_sha2.data\n\
         //\n\
         // Generator: docs/c-test-migration-plan.md Phase A (xtask).\n\n\
         #![cfg(feature = \"sha2\")]\n\n\
         use hitls_crypto::sha2::{Sha224, Sha256, Sha384, Sha512};\n\n",
    );
}

fn write_footer(out: &mut String, stats: &EmitStats, total: usize) {
    writeln!(
        out,
        "\n// Generation summary: {emitted} emitted / {api} API-surface skipped (N/A in Rust) \
         / {unk} unknown / {unsupported} unsupported alg / {total} total C cases.",
        emitted = stats.emitted,
        api = stats.skipped_api,
        unk = stats.skipped_unknown,
        unsupported = stats.skipped_unsupported_alg,
        total = total,
    )
    .unwrap();
}

fn emit_one_shot(out: &mut String, case: &TestCase, stats: &mut EmitStats) {
    // Expected: 3 args = alg, input, expected.
    let Some((alg, input, expected)) = three_arg(case) else {
        stats.skipped_unknown += 1;
        return;
    };
    let Some(rust_ty) = alg_to_rust(alg) else {
        stats.skipped_unsupported_alg += 1;
        return;
    };
    let fn_name = format!("tc_line{}_{}_one_shot", case.line, alg_lower(rust_ty));
    write_test_doc(out, case, "one-shot KAT");
    writeln!(out, "#[test]").unwrap();
    writeln!(out, "fn {fn_name}() {{").unwrap();
    writeln!(out, "    let input: &[u8] = {};", format_byte_slice(input)).unwrap();
    writeln!(
        out,
        "    let expected: &[u8] = {};",
        format_byte_slice(expected)
    )
    .unwrap();
    writeln!(out, "    let actual = {rust_ty}::digest(input).unwrap();").unwrap();
    writeln!(out, "    assert_eq!(actual.as_ref(), expected);").unwrap();
    writeln!(out, "}}\n").unwrap();
    stats.emitted += 1;
}

fn emit_empty_input(out: &mut String, case: &TestCase, stats: &mut EmitStats) {
    // Expected: 2 args = alg, expected.
    if case.args.len() != 2 {
        stats.skipped_unknown += 1;
        return;
    }
    let Some(alg) = case.args[0].as_symbol() else {
        stats.skipped_unknown += 1;
        return;
    };
    let Some(expected) = case.args[1].as_hex() else {
        stats.skipped_unknown += 1;
        return;
    };
    let Some(rust_ty) = alg_to_rust(alg) else {
        stats.skipped_unsupported_alg += 1;
        return;
    };
    let fn_name = format!("tc_line{}_{}_empty_input", case.line, alg_lower(rust_ty));
    write_test_doc(out, case, "init+final, no update");
    writeln!(out, "#[test]").unwrap();
    writeln!(out, "fn {fn_name}() {{").unwrap();
    writeln!(
        out,
        "    let expected: &[u8] = {};",
        format_byte_slice(expected)
    )
    .unwrap();
    writeln!(out, "    let actual = {rust_ty}::digest(&[]).unwrap();").unwrap();
    writeln!(out, "    assert_eq!(actual.as_ref(), expected);").unwrap();
    writeln!(out, "}}\n").unwrap();
    stats.emitted += 1;
}

fn emit_multi_block(out: &mut String, case: &TestCase, stats: &mut EmitStats) {
    // Expected: 5 args = alg, part1, part2, part3, expected.
    if case.args.len() != 5 {
        stats.skipped_unknown += 1;
        return;
    }
    let Some(alg) = case.args[0].as_symbol() else {
        stats.skipped_unknown += 1;
        return;
    };
    let parts = [
        case.args[1].as_hex(),
        case.args[2].as_hex(),
        case.args[3].as_hex(),
    ];
    let Some(expected) = case.args[4].as_hex() else {
        stats.skipped_unknown += 1;
        return;
    };
    if parts.iter().any(|p| p.is_none()) {
        stats.skipped_unknown += 1;
        return;
    }
    let parts: Vec<&[u8]> = parts.iter().map(|p| p.unwrap()).collect();

    let Some(rust_ty) = alg_to_rust(alg) else {
        stats.skipped_unsupported_alg += 1;
        return;
    };
    let fn_name = format!("tc_line{}_{}_multi_block", case.line, alg_lower(rust_ty));
    write_test_doc(out, case, "split update across 3 chunks");
    writeln!(out, "#[test]").unwrap();
    writeln!(out, "fn {fn_name}() {{").unwrap();
    for (i, part) in parts.iter().enumerate() {
        writeln!(out, "    let part{i}: &[u8] = {};", format_byte_slice(part)).unwrap();
    }
    writeln!(
        out,
        "    let expected: &[u8] = {};",
        format_byte_slice(expected)
    )
    .unwrap();
    writeln!(out, "    let mut ctx = {rust_ty}::new();").unwrap();
    for i in 0..parts.len() {
        writeln!(out, "    ctx.update(part{i}).unwrap();").unwrap();
    }
    writeln!(out, "    let actual = ctx.finish().unwrap();").unwrap();
    writeln!(out, "    assert_eq!(actual.as_ref(), expected);").unwrap();
    writeln!(out, "}}\n").unwrap();
    stats.emitted += 1;
}

fn three_arg(case: &TestCase) -> Option<(&str, &[u8], &[u8])> {
    if case.args.len() != 3 {
        return None;
    }
    Some((
        case.args[0].as_symbol()?,
        case.args[1].as_hex()?,
        case.args[2].as_hex()?,
    ))
}

fn write_test_doc(out: &mut String, case: &TestCase, kind: &str) {
    if let Some(desc) = &case.description {
        writeln!(out, "/// {desc}").unwrap();
    }
    writeln!(
        out,
        "/// C source: {} (line {}, {kind})",
        case.tc_name, case.line
    )
    .unwrap();
}

// ---------------------------------------------------------------------------
// Single-algorithm digest families (MD5 / SHA-1 / SM3).
//
// Unlike the SHA-2/SHA-3 EAL files, these `.data` files fix the algorithm
// per file: the primary KAT rows carry NO `CRYPT_MD_*` algid argument, and
// the TC-number -> family mapping is inconsistent across files (MD5's empty
// case is FUNC_TC001, SM3's is FUNC_TC001 too, SHA-1's is a FUN_TC001 row
// with an empty input). So these are classified by argument SHAPE plus a
// digest-length guard on the expected output, not by TC number. Rows that
// DO carry an algid (COPY_CTX / DEFAULT_PROVIDER / EAL-with-algid) duplicate
// the no-algid vectors and are routed to API-surface to avoid redundancy.
// ---------------------------------------------------------------------------

/// Per-algorithm parameters for a single-algorithm digest file.
struct DigestCfg {
    /// The xtask `--algo` name (used in the generated header comment).
    algo: &'static str,
    /// `Cargo.toml` feature gating the algorithm.
    feature: &'static str,
    /// Fully-qualified Rust import (e.g. `hitls_crypto::md5::Md5`).
    import: &'static str,
    /// The Rust type name (e.g. `Md5`).
    rust_ty: &'static str,
    /// Source C `.data` file basename (header comment only).
    data_file: &'static str,
    /// Digest output length in bytes — used as the expected-output guard.
    dlen: usize,
}

const MD5_CFG: DigestCfg = DigestCfg {
    algo: "md5",
    feature: "md5",
    import: "hitls_crypto::md5::Md5",
    rust_ty: "Md5",
    data_file: "test_suite_sdv_eal_md5.data",
    dlen: 16,
};

const SHA1_CFG: DigestCfg = DigestCfg {
    algo: "sha1",
    feature: "sha1",
    import: "hitls_crypto::sha1::Sha1",
    rust_ty: "Sha1",
    data_file: "test_suite_sdv_eal_md_sha1.data",
    dlen: 20,
};

const SM3_CFG: DigestCfg = DigestCfg {
    algo: "sm3",
    feature: "sm3",
    import: "hitls_crypto::sm3::Sm3",
    rust_ty: "Sm3",
    data_file: "test_suite_sdv_eal_sm3.data",
    dlen: 32,
};

pub fn emit_md5_kat(cases: &[TestCase]) -> (String, EmitStats) {
    emit_md_family(cases, &MD5_CFG)
}

pub fn emit_sha1_kat(cases: &[TestCase]) -> (String, EmitStats) {
    emit_md_family(cases, &SHA1_CFG)
}

pub fn emit_sm3_kat(cases: &[TestCase]) -> (String, EmitStats) {
    emit_md_family(cases, &SM3_CFG)
}

/// The kind of single-algorithm digest KAT a row encodes, decided by
/// argument shape (see module comment above).
enum MdCase<'a> {
    /// One hex arg = the digest of the empty input.
    Empty {
        expected: &'a [u8],
    },
    /// Two hex args = input + expected (one-shot digest).
    OneShot {
        input: &'a [u8],
        expected: &'a [u8],
    },
    /// N >= 1 input parts + expected (split-update across chunks).
    MultiBlock {
        parts: Vec<&'a [u8]>,
        expected: &'a [u8],
    },
    /// Lifecycle / duplicate-with-algid / no-data row — N/A in Rust.
    ApiSurface,
    Unknown,
}

fn classify_md<'a>(case: &'a TestCase, dlen: usize) -> MdCase<'a> {
    let name = &case.tc_name;
    if name.contains("_API_TC")
        || name.contains("_COPY_CTX_")
        || name.contains("_DEFAULT_PROVIDER_")
        || name.contains("_MB_")
    {
        return MdCase::ApiSurface;
    }
    if case.args.is_empty() {
        // No-data lifecycle row (e.g. a bare `FUNC_TC00N:`).
        return MdCase::ApiSurface;
    }
    // An algid-prefixed row (COPY_CTX / DEFAULT_PROVIDER / EAL-with-algid)
    // duplicates a no-algid KAT vector — skip to avoid redundancy.
    if case.args[0].as_symbol().is_some() {
        return MdCase::ApiSurface;
    }
    // All args must be hex for an arg-shape KAT.
    let hexes: Option<Vec<&[u8]>> = case.args.iter().map(|a| a.as_hex()).collect();
    let Some(hexes) = hexes else {
        return MdCase::Unknown;
    };
    match hexes.len() {
        1 if hexes[0].len() == dlen => MdCase::Empty { expected: hexes[0] },
        2 if hexes[1].len() == dlen => MdCase::OneShot {
            input: hexes[0],
            expected: hexes[1],
        },
        n if n >= 3 && hexes[n - 1].len() == dlen => MdCase::MultiBlock {
            parts: hexes[..n - 1].to_vec(),
            expected: hexes[n - 1],
        },
        _ => MdCase::Unknown,
    }
}

fn emit_md_family(cases: &[TestCase], cfg: &DigestCfg) -> (String, EmitStats) {
    let mut out = String::new();
    let mut stats = EmitStats::default();

    writeln!(
        out,
        "// This file is GENERATED by `cargo xtask migrate-c-tests --algo {algo}`.\n\
         // DO NOT EDIT BY HAND. Source: openhitls C SDV {data}\n\
         //\n\
         // Generator: docs/c-test-migration-plan.md Phase A (xtask).\n\n\
         #![cfg(feature = \"{feat}\")]\n\n\
         use {import};\n",
        algo = cfg.algo,
        data = cfg.data_file,
        feat = cfg.feature,
        import = cfg.import,
    )
    .unwrap();

    for case in cases {
        match classify_md(case, cfg.dlen) {
            MdCase::Empty { expected } => {
                write_test_doc(&mut out, case, "init+final, no update");
                writeln!(out, "#[test]").unwrap();
                writeln!(out, "fn tc_line{}_empty_input() {{", case.line).unwrap();
                writeln!(
                    out,
                    "    let expected: &[u8] = {};",
                    format_byte_slice(expected)
                )
                .unwrap();
                writeln!(
                    out,
                    "    let actual = {}::digest(&[]).unwrap();",
                    cfg.rust_ty
                )
                .unwrap();
                writeln!(out, "    assert_eq!(actual.as_ref(), expected);").unwrap();
                writeln!(out, "}}\n").unwrap();
                stats.emitted += 1;
            }
            MdCase::OneShot { input, expected } => {
                write_test_doc(&mut out, case, "one-shot KAT");
                writeln!(out, "#[test]").unwrap();
                writeln!(out, "fn tc_line{}_one_shot() {{", case.line).unwrap();
                writeln!(out, "    let input: &[u8] = {};", format_byte_slice(input)).unwrap();
                writeln!(
                    out,
                    "    let expected: &[u8] = {};",
                    format_byte_slice(expected)
                )
                .unwrap();
                writeln!(
                    out,
                    "    let actual = {}::digest(input).unwrap();",
                    cfg.rust_ty
                )
                .unwrap();
                writeln!(out, "    assert_eq!(actual.as_ref(), expected);").unwrap();
                writeln!(out, "}}\n").unwrap();
                stats.emitted += 1;
            }
            MdCase::MultiBlock { parts, expected } => {
                write_test_doc(&mut out, case, "split update across chunks");
                writeln!(out, "#[test]").unwrap();
                writeln!(out, "fn tc_line{}_multi_block() {{", case.line).unwrap();
                for (i, part) in parts.iter().enumerate() {
                    writeln!(out, "    let part{i}: &[u8] = {};", format_byte_slice(part)).unwrap();
                }
                writeln!(
                    out,
                    "    let expected: &[u8] = {};",
                    format_byte_slice(expected)
                )
                .unwrap();
                writeln!(out, "    let mut ctx = {}::new();", cfg.rust_ty).unwrap();
                for i in 0..parts.len() {
                    writeln!(out, "    ctx.update(part{i}).unwrap();").unwrap();
                }
                writeln!(out, "    let actual = ctx.finish().unwrap();").unwrap();
                writeln!(out, "    assert_eq!(actual.as_ref(), expected);").unwrap();
                writeln!(out, "}}\n").unwrap();
                stats.emitted += 1;
            }
            MdCase::ApiSurface => stats.skipped_api += 1,
            MdCase::Unknown => stats.skipped_unknown += 1,
        }
    }

    write_footer(&mut out, &stats, cases.len());
    (out, stats)
}
