use std::collections::BTreeSet;
use std::fmt::Write;

use crate::digest::EmitStats;
use crate::parser::{format_byte_slice, TestCase};

// ---------------------------------------------------------------------------
// KDF KAT migration (HKDF / PBKDF2 / scrypt / TLS 1.2 PRF).
//
// Each C `.data` file has its own argument layout (confirmed against the C
// test-function signatures), all deterministic byte-exact KATs:
//   HKDF      : (macAlg, ikm, salt, info, expected)
//   PBKDF2    : (macAlg, password, salt, iterations, expected)
//   scrypt    : (password, salt, N, r, p, expected)   [no macAlg — fixed]
//   TLS12 PRF : (macAlg, secret, label, seed, expected)
//
// Output length is taken from the expected vector's length. Integer params
// (iterations / N / r / p) are unquoted in the `.data` file, so the parser
// surfaces them as `Arg::Symbol`. COPY_CTX / DEFAULT_PROVIDER / lifecycle
// rows duplicate the KAT vectors or test C-only context APIs → API-surface.
// ---------------------------------------------------------------------------

/// Map a C HMAC algorithm symbol to (Rust hash type, feature, output length).
fn mac_to_hash(symbol: &str) -> Option<(&'static str, &'static str, usize)> {
    match symbol {
        "CRYPT_MAC_HMAC_MD5" => Some(("Md5", "md5", 16)),
        "CRYPT_MAC_HMAC_SHA1" => Some(("Sha1", "sha1", 20)),
        "CRYPT_MAC_HMAC_SHA224" => Some(("Sha224", "sha2", 28)),
        "CRYPT_MAC_HMAC_SHA256" => Some(("Sha256", "sha2", 32)),
        "CRYPT_MAC_HMAC_SHA384" => Some(("Sha384", "sha2", 48)),
        "CRYPT_MAC_HMAC_SHA512" => Some(("Sha512", "sha2", 64)),
        _ => None,
    }
}

fn hash_feature(rust_ty: &str) -> &'static str {
    match rust_ty {
        "Md5" => "md5",
        "Sha1" => "sha1",
        _ => "sha2",
    }
}

fn hash_lower(rust_ty: &str) -> &'static str {
    match rust_ty {
        "Md5" => "md5",
        "Sha1" => "sha1",
        "Sha224" => "sha224",
        "Sha256" => "sha256",
        "Sha384" => "sha384",
        "Sha512" => "sha512",
        _ => "unknown",
    }
}

/// Emit the file header for an HMAC-keyed KDF (HKDF / PBKDF2): the file-level
/// `cfg(all(...))` gate over every feature the emitted tests touch, plus the
/// per-hash imports.
fn write_hashed_header(
    out: &mut String,
    algo: &str,
    data_file: &str,
    base_feature: &'static str,
    api_path: &str,
    used_hashes: &BTreeSet<&'static str>,
) {
    writeln!(
        out,
        "// This file is GENERATED by `cargo xtask migrate-c-tests --algo {algo}`.\n\
         // DO NOT EDIT BY HAND. Source: openhitls C SDV {data_file}\n\
         //\n\
         // Generator: docs/c-test-migration-plan.md Phase A (xtask)."
    )
    .unwrap();

    let mut features: BTreeSet<&'static str> = BTreeSet::new();
    features.insert(base_feature);
    for ty in used_hashes {
        features.insert(hash_feature(ty));
    }
    let parts: Vec<String> = features
        .iter()
        .map(|f| format!("feature = \"{f}\""))
        .collect();
    writeln!(out, "#![cfg(all({}))]\n", parts.join(", ")).unwrap();

    writeln!(out, "use {api_path};").unwrap();
    out.push_str("use hitls_crypto::provider::Digest;\n");
    let mut sha2: Vec<&str> = Vec::new();
    for ty in used_hashes {
        match hash_feature(ty) {
            "sha2" => sha2.push(ty),
            "md5" => out.push_str("use hitls_crypto::md5::Md5;\n"),
            "sha1" => out.push_str("use hitls_crypto::sha1::Sha1;\n"),
            _ => {}
        }
    }
    if !sha2.is_empty() {
        writeln!(out, "use hitls_crypto::sha2::{{{}}};", sha2.join(", ")).unwrap();
    }
    out.push('\n');
}

fn write_footer(out: &mut String, stats: &EmitStats, total: usize) {
    writeln!(
        out,
        "\n// Generation summary: {emitted} emitted / {api} API-surface skipped (N/A in Rust) \
         / {unk} unknown / {unsupported} unsupported alg / {total} total C cases.",
        emitted = stats.emitted,
        api = stats.skipped_api,
        unk = stats.skipped_unknown,
        unsupported = stats.skipped_unsupported_alg,
        total = total,
    )
    .unwrap();
}

fn write_doc(out: &mut String, case: &TestCase, kind: &str) {
    if let Some(desc) = &case.description {
        writeln!(out, "/// {desc}").unwrap();
    }
    writeln!(
        out,
        "/// C source: {} (line {}, {kind})",
        case.tc_name, case.line
    )
    .unwrap();
}

/// True for the C-only lifecycle / provider rows shared by every KDF file.
fn is_api_surface(tc_name: &str) -> bool {
    tc_name.contains("_API_TC")
        || tc_name.contains("_COPY_CTX_")
        || tc_name.contains("_DUP_CTX_")
        || tc_name.contains("_DEFAULT_PROVIDER_")
}

// ---------------------------------------------------------------------------
// HKDF — (macAlg, ikm, salt, info, expected)
// ---------------------------------------------------------------------------

pub fn emit_hkdf_kat(cases: &[TestCase]) -> (String, EmitStats) {
    let mut body = String::new();
    let mut stats = EmitStats::default();
    let mut used: BTreeSet<&'static str> = BTreeSet::new();

    for case in cases {
        if is_api_surface(&case.tc_name) || !case.tc_name.contains("_FUN_TC001") {
            stats.skipped_api += 1;
            continue;
        }
        let (Some(alg), Some(ikm), Some(salt), Some(info), Some(expected)) = (
            case.args.first().and_then(|a| a.as_symbol()),
            case.args.get(1).and_then(|a| a.as_hex()),
            case.args.get(2).and_then(|a| a.as_hex()),
            case.args.get(3).and_then(|a| a.as_hex()),
            case.args.get(4).and_then(|a| a.as_hex()),
        ) else {
            stats.skipped_unknown += 1;
            continue;
        };
        let Some((ty, _feat, hlen)) = mac_to_hash(alg) else {
            stats.skipped_unsupported_alg += 1;
            continue;
        };
        used.insert(ty);
        write_doc(&mut body, case, "HKDF extract+expand KAT");
        writeln!(body, "#[test]").unwrap();
        writeln!(body, "fn tc_line{}_hkdf_{}() {{", case.line, hash_lower(ty)).unwrap();
        writeln!(body, "    let ikm: &[u8] = {};", format_byte_slice(ikm)).unwrap();
        writeln!(body, "    let salt: &[u8] = {};", format_byte_slice(salt)).unwrap();
        writeln!(body, "    let info: &[u8] = {};", format_byte_slice(info)).unwrap();
        writeln!(
            body,
            "    let expected: &[u8] = {};",
            format_byte_slice(expected)
        )
        .unwrap();
        writeln!(
            body,
            "    let factory = || -> Box<dyn Digest> {{ Box::new({ty}::new()) }};"
        )
        .unwrap();
        writeln!(
            body,
            "    let hkdf = Hkdf::new_with_factory(salt, ikm, factory, {hlen}).unwrap();"
        )
        .unwrap();
        writeln!(
            body,
            "    let actual = hkdf.expand(info, expected.len()).unwrap();"
        )
        .unwrap();
        writeln!(body, "    assert_eq!(actual.as_slice(), expected);").unwrap();
        writeln!(body, "}}\n").unwrap();
        stats.emitted += 1;
    }

    let mut out = String::new();
    write_hashed_header(
        &mut out,
        "hkdf",
        "test_suite_sdv_eal_kdf_hkdf.data",
        "hkdf",
        "hitls_crypto::hkdf::Hkdf",
        &used,
    );
    out.push_str(&body);
    write_footer(&mut out, &stats, cases.len());
    (out, stats)
}

// ---------------------------------------------------------------------------
// PBKDF2 — (macAlg, password, salt, iterations, expected)
// ---------------------------------------------------------------------------

pub fn emit_pbkdf2_kat(cases: &[TestCase]) -> (String, EmitStats) {
    let mut body = String::new();
    let mut stats = EmitStats::default();
    let mut used: BTreeSet<&'static str> = BTreeSet::new();

    for case in cases {
        if is_api_surface(&case.tc_name) || !case.tc_name.contains("_FUN_TC001") {
            stats.skipped_api += 1;
            continue;
        }
        let (Some(alg), Some(pw), Some(salt), Some(iter_sym), Some(expected)) = (
            case.args.first().and_then(|a| a.as_symbol()),
            case.args.get(1).and_then(|a| a.as_hex()),
            case.args.get(2).and_then(|a| a.as_hex()),
            case.args.get(3).and_then(|a| a.as_symbol()),
            case.args.get(4).and_then(|a| a.as_hex()),
        ) else {
            stats.skipped_unknown += 1;
            continue;
        };
        let Ok(iters) = iter_sym.parse::<u32>() else {
            stats.skipped_unknown += 1;
            continue;
        };
        let Some((ty, _feat, _hlen)) = mac_to_hash(alg) else {
            stats.skipped_unsupported_alg += 1;
            continue;
        };
        used.insert(ty);
        write_doc(&mut body, case, "PBKDF2-HMAC KAT");
        writeln!(body, "#[test]").unwrap();
        writeln!(
            body,
            "fn tc_line{}_pbkdf2_{}() {{",
            case.line,
            hash_lower(ty)
        )
        .unwrap();
        writeln!(body, "    let password: &[u8] = {};", format_byte_slice(pw)).unwrap();
        writeln!(body, "    let salt: &[u8] = {};", format_byte_slice(salt)).unwrap();
        writeln!(
            body,
            "    let expected: &[u8] = {};",
            format_byte_slice(expected)
        )
        .unwrap();
        writeln!(
            body,
            "    let factory = || -> Box<dyn Digest> {{ Box::new({ty}::new()) }};"
        )
        .unwrap();
        writeln!(
            body,
            "    let actual = pbkdf2_with_hmac(factory, password, salt, {iters}, expected.len()).unwrap();"
        )
        .unwrap();
        writeln!(body, "    assert_eq!(actual.as_slice(), expected);").unwrap();
        writeln!(body, "}}\n").unwrap();
        stats.emitted += 1;
    }

    let mut out = String::new();
    write_hashed_header(
        &mut out,
        "pbkdf2",
        "test_suite_sdv_eal_kdf_pbkdf2.data",
        "pbkdf2",
        "hitls_crypto::pbkdf2::pbkdf2_with_hmac",
        &used,
    );
    out.push_str(&body);
    write_footer(&mut out, &stats, cases.len());
    (out, stats)
}

// ---------------------------------------------------------------------------
// scrypt — (password, salt, N, r, p, expected); no macAlg.
// FUN_TC002(N, r, p) is a parameter-validation test (error paths) → API.
// ---------------------------------------------------------------------------

pub fn emit_scrypt_kat(cases: &[TestCase]) -> (String, EmitStats) {
    let mut body = String::new();
    let mut stats = EmitStats::default();

    for case in cases {
        if is_api_surface(&case.tc_name) || !case.tc_name.contains("_FUN_TC001") {
            stats.skipped_api += 1;
            continue;
        }
        let (Some(pw), Some(salt), Some(n_sym), Some(r_sym), Some(p_sym), Some(expected)) = (
            case.args.first().and_then(|a| a.as_hex()),
            case.args.get(1).and_then(|a| a.as_hex()),
            case.args.get(2).and_then(|a| a.as_symbol()),
            case.args.get(3).and_then(|a| a.as_symbol()),
            case.args.get(4).and_then(|a| a.as_symbol()),
            case.args.get(5).and_then(|a| a.as_hex()),
        ) else {
            stats.skipped_unknown += 1;
            continue;
        };
        let (Ok(n), Ok(r), Ok(p)) = (
            n_sym.parse::<u32>(),
            r_sym.parse::<u32>(),
            p_sym.parse::<u32>(),
        ) else {
            stats.skipped_unknown += 1;
            continue;
        };
        write_doc(&mut body, case, "scrypt KAT");
        writeln!(body, "#[test]").unwrap();
        writeln!(body, "fn tc_line{}_scrypt() {{", case.line).unwrap();
        writeln!(body, "    let password: &[u8] = {};", format_byte_slice(pw)).unwrap();
        writeln!(body, "    let salt: &[u8] = {};", format_byte_slice(salt)).unwrap();
        writeln!(
            body,
            "    let expected: &[u8] = {};",
            format_byte_slice(expected)
        )
        .unwrap();
        writeln!(
            body,
            "    let actual = scrypt(password, salt, {n}, {r}, {p}, expected.len()).unwrap();"
        )
        .unwrap();
        writeln!(body, "    assert_eq!(actual.as_slice(), expected);").unwrap();
        writeln!(body, "}}\n").unwrap();
        stats.emitted += 1;
    }

    let mut out = String::new();
    writeln!(
        out,
        "// This file is GENERATED by `cargo xtask migrate-c-tests --algo scrypt`.\n\
         // DO NOT EDIT BY HAND. Source: openhitls C SDV test_suite_sdv_eal_kdf_scrypt.data\n\
         //\n\
         // Generator: docs/c-test-migration-plan.md Phase A (xtask).\n\
         #![cfg(feature = \"scrypt\")]\n\n\
         use hitls_crypto::scrypt::scrypt;\n"
    )
    .unwrap();
    out.push_str(&body);
    write_footer(&mut out, &stats, cases.len());
    (out, stats)
}

// ---------------------------------------------------------------------------
// TLS 1.2 PRF — (macAlg, secret, label, seed, expected). Lives in hitls-tls.
// `prf` concatenates label‖seed internally, so we pass label="" and seed =
// (label ++ seed) to reproduce the identical P_hash input without needing
// the label to be valid UTF-8.
//
// HashAlgId variants in `hitls_tls::crypt`: Sha1, Sha256, Sha384, Sha512
// (the SHA-512 variant is migration-test-only — TLS 1.2 itself never
// negotiates a SHA-512 PRF, the entry is added so the C SDV
// `CRYPT_MAC_HMAC_SHA512` PRF vectors can be migrated byte-exactly).
// ---------------------------------------------------------------------------

fn mac_to_hashalgid(symbol: &str) -> Option<&'static str> {
    match symbol {
        "CRYPT_MAC_HMAC_SHA256" => Some("Sha256"),
        "CRYPT_MAC_HMAC_SHA384" => Some("Sha384"),
        "CRYPT_MAC_HMAC_SHA512" => Some("Sha512"),
        "CRYPT_MAC_HMAC_SHA1" => Some("Sha1"),
        _ => None,
    }
}

pub fn emit_kdf_tls12_kat(cases: &[TestCase]) -> (String, EmitStats) {
    let mut body = String::new();
    let mut stats = EmitStats::default();

    for case in cases {
        if is_api_surface(&case.tc_name) || !case.tc_name.contains("_FUN_TC001") {
            stats.skipped_api += 1;
            continue;
        }
        let (Some(alg), Some(secret), Some(label), Some(seed), Some(expected)) = (
            case.args.first().and_then(|a| a.as_symbol()),
            case.args.get(1).and_then(|a| a.as_hex()),
            case.args.get(2).and_then(|a| a.as_hex()),
            case.args.get(3).and_then(|a| a.as_hex()),
            case.args.get(4).and_then(|a| a.as_hex()),
        ) else {
            stats.skipped_unknown += 1;
            continue;
        };
        let Some(variant) = mac_to_hashalgid(alg) else {
            stats.skipped_unsupported_alg += 1;
            continue;
        };
        // P_hash input is label ‖ seed; fold both into a single seed slice.
        let mut label_seed = label.to_vec();
        label_seed.extend_from_slice(seed);
        write_doc(&mut body, case, "TLS 1.2 PRF KAT");
        writeln!(body, "#[test]").unwrap();
        writeln!(
            body,
            "fn tc_line{}_tls12_prf_{}() {{",
            case.line,
            variant.to_lowercase()
        )
        .unwrap();
        writeln!(
            body,
            "    let secret: &[u8] = {};",
            format_byte_slice(secret)
        )
        .unwrap();
        writeln!(
            body,
            "    let label_seed: &[u8] = {};",
            format_byte_slice(&label_seed)
        )
        .unwrap();
        writeln!(
            body,
            "    let expected: &[u8] = {};",
            format_byte_slice(expected)
        )
        .unwrap();
        writeln!(
            body,
            "    let actual = prf(HashAlgId::{variant}, secret, \"\", label_seed, expected.len()).unwrap();"
        )
        .unwrap();
        writeln!(body, "    assert_eq!(actual.as_slice(), expected);").unwrap();
        writeln!(body, "}}\n").unwrap();
        stats.emitted += 1;
    }

    let mut out = String::new();
    out.push_str(
        "// This file is GENERATED by `cargo xtask migrate-c-tests --algo kdf-tls12`.\n\
         // DO NOT EDIT BY HAND. Source: openhitls C SDV test_suite_sdv_eal_kdf_tls12.data\n\
         //\n\
         // Generator: docs/c-test-migration-plan.md Phase A (xtask).\n\n\
         use hitls_tls::crypt::prf::prf;\n\
         use hitls_tls::crypt::HashAlgId;\n\n",
    );
    out.push_str(&body);
    write_footer(&mut out, &stats, cases.len());
    (out, stats)
}
