use std::fmt::Write;

use crate::digest::EmitStats;
use crate::parser::{format_byte_slice, TestCase};

// ---------------------------------------------------------------------------
// PQC KEM decapsulation KAT migration (FrodoKEM).
//
// C `ENCAPS_DECAPS_FUNC_TC001` rows publish (algId, seed, testEk, testDk,
// testCt, testSs). The decapsulation direction is deterministic: load the
// vector's `testDk` and check `decapsulate(testCt) == testSs`. Unblocked by
// the I145 FrodoKEM pack/unpack fix (MSB-first, reference-compatible) +
// `FrodoKemKeyPair::from_decapsulation_key`.
//
// McEliece is NOT migrated yet — its decaps still diverges from the reference
// (a separate, deeper code-based-scheme serialization issue — see na-list).
// ---------------------------------------------------------------------------

fn frodo_param(symbol: &str) -> Option<&'static str> {
    match symbol {
        "CRYPT_KEM_TYPE_FRODOKEM_640_SHAKE" => Some("FrodoKem640Shake"),
        "CRYPT_KEM_TYPE_FRODOKEM_976_SHAKE" => Some("FrodoKem976Shake"),
        "CRYPT_KEM_TYPE_FRODOKEM_1344_SHAKE" => Some("FrodoKem1344Shake"),
        "CRYPT_KEM_TYPE_FRODOKEM_640_AES" => Some("FrodoKem640Aes"),
        "CRYPT_KEM_TYPE_FRODOKEM_976_AES" => Some("FrodoKem976Aes"),
        "CRYPT_KEM_TYPE_FRODOKEM_1344_AES" => Some("FrodoKem1344Aes"),
        _ => None, // eFrodoKEM variants: no fixed-vector reference rows here
    }
}

fn write_doc(out: &mut String, case: &TestCase, kind: &str) {
    if let Some(desc) = &case.description {
        writeln!(out, "/// {desc}").unwrap();
    }
    writeln!(
        out,
        "/// C source: {} (line {}, {kind})",
        case.tc_name, case.line
    )
    .unwrap();
}

fn write_footer(out: &mut String, stats: &EmitStats, total: usize) {
    writeln!(
        out,
        "\n// Generation summary: {emitted} emitted / {api} API-surface skipped (N/A in Rust) \
         / {unk} unknown / {unsupported} unsupported alg / {total} total C cases.",
        emitted = stats.emitted,
        api = stats.skipped_api,
        unk = stats.skipped_unknown,
        unsupported = stats.skipped_unsupported_alg,
        total = total,
    )
    .unwrap();
}

pub fn emit_frodokem_kat(cases: &[TestCase]) -> (String, EmitStats) {
    let mut body = String::new();
    let mut stats = EmitStats::default();

    for case in cases {
        if !case.tc_name.contains("_ENCAPS_DECAPS_FUNC_TC001") {
            stats.skipped_api += 1;
            continue;
        }
        // Layout: (param, seed, testEk, testDk, testCt, testSs).
        let (Some(param_sym), Some(dk), Some(ct), Some(ss)) = (
            case.args.first().and_then(|a| a.as_symbol()),
            case.args.get(3).and_then(|a| a.as_hex()),
            case.args.get(4).and_then(|a| a.as_hex()),
            case.args.get(5).and_then(|a| a.as_hex()),
        ) else {
            stats.skipped_unknown += 1;
            continue;
        };
        let Some(variant) = frodo_param(param_sym) else {
            stats.skipped_unsupported_alg += 1;
            continue;
        };
        write_doc(&mut body, case, "FrodoKEM decapsulation KAT");
        writeln!(body, "#[test]").unwrap();
        writeln!(
            body,
            "fn tc_line{}_frodokem_{}_decaps() {{",
            case.line,
            variant.to_lowercase()
        )
        .unwrap();
        writeln!(body, "    let dk: &[u8] = {};", format_byte_slice(dk)).unwrap();
        writeln!(body, "    let ct: &[u8] = {};", format_byte_slice(ct)).unwrap();
        writeln!(
            body,
            "    let expected_ss: &[u8] = {};",
            format_byte_slice(ss)
        )
        .unwrap();
        writeln!(
            body,
            "    let kp = FrodoKemKeyPair::from_decapsulation_key(FrodoKemParamId::{variant}, dk).unwrap();"
        )
        .unwrap();
        writeln!(body, "    let ss = kp.decapsulate(ct).unwrap();").unwrap();
        writeln!(body, "    assert_eq!(ss.as_slice(), expected_ss);").unwrap();
        writeln!(body, "}}\n").unwrap();
        stats.emitted += 1;
    }

    let mut out = String::new();
    out.push_str(
        "// This file is GENERATED by `cargo xtask migrate-c-tests --algo frodokem`.\n\
         // DO NOT EDIT BY HAND. Source: openhitls C SDV test_suite_sdv_frodokem.data\n\
         //\n\
         // Generator: docs/c-test-migration-plan.md Phase A (xtask).\n\
         #![cfg(feature = \"frodokem\")]\n\n\
         use hitls_crypto::frodokem::FrodoKemKeyPair;\n\
         use hitls_types::FrodoKemParamId;\n\n",
    );
    out.push_str(&body);
    write_footer(&mut out, &stats, cases.len());
    (out, stats)
}
