use std::collections::BTreeSet;
use std::fmt::Write;

use crate::digest::EmitStats;
use crate::parser::{format_byte_slice, TestCase};

pub fn emit_hmac_kat(cases: &[TestCase]) -> (String, EmitStats) {
    let mut body = String::new();
    let mut stats = EmitStats::default();
    let mut used_hashes: BTreeSet<&'static str> = BTreeSet::new();

    for case in cases {
        let kind = classify(&case.tc_name);
        match kind {
            CaseKind::OneShot => {
                emit_one_shot(&mut body, case, &mut stats, &mut used_hashes);
            }
            CaseKind::ApiSurface => stats.skipped_api += 1,
            CaseKind::Unknown => stats.skipped_unknown += 1,
        }
    }

    let mut out = String::new();
    write_header(&mut out, &used_hashes);
    out.push_str(&body);
    write_footer(&mut out, &stats, cases.len());
    (out, stats)
}

#[derive(Debug, Clone, Copy)]
enum CaseKind {
    /// FUN_TC001: alg + key + msg + expected (one-shot HMAC KAT).
    OneShot,
    /// API_*, COPY_CTX_*, DUP_CTX_*, DEFAULT_PROVIDER_*, FUN_TC002/3 (split + ctx-reuse).
    ApiSurface,
    Unknown,
}

fn classify(tc_name: &str) -> CaseKind {
    // Architectural / context-lifecycle patterns first.
    if tc_name.contains("_API_TC")
        || tc_name.contains("_COPY_CTX_")
        || tc_name.contains("_DUP_CTX_")
        || tc_name.contains("_DEFAULT_PROVIDER_")
        || tc_name.contains("_FUN_TC002")
        || tc_name.contains("_FUN_TC003")
    {
        return CaseKind::ApiSurface;
    }
    if tc_name.contains("_FUN_TC001") {
        CaseKind::OneShot
    } else {
        CaseKind::Unknown
    }
}

/// Map C HMAC algorithm symbol to (Rust hash type, feature name).
fn alg_to_rust(symbol: &str) -> Option<(&'static str, &'static str)> {
    match symbol {
        "CRYPT_MAC_HMAC_MD5" => Some(("Md5", "md5")),
        "CRYPT_MAC_HMAC_SHA1" => Some(("Sha1", "sha1")),
        "CRYPT_MAC_HMAC_SHA224" => Some(("Sha224", "sha2")),
        "CRYPT_MAC_HMAC_SHA256" => Some(("Sha256", "sha2")),
        "CRYPT_MAC_HMAC_SHA384" => Some(("Sha384", "sha2")),
        "CRYPT_MAC_HMAC_SHA512" => Some(("Sha512", "sha2")),
        "CRYPT_MAC_HMAC_SM3" => Some(("Sm3", "sm3")),
        "CRYPT_MAC_HMAC_SHA3_224" => Some(("Sha3_224", "sha3")),
        "CRYPT_MAC_HMAC_SHA3_256" => Some(("Sha3_256", "sha3")),
        "CRYPT_MAC_HMAC_SHA3_384" => Some(("Sha3_384", "sha3")),
        "CRYPT_MAC_HMAC_SHA3_512" => Some(("Sha3_512", "sha3")),
        _ => None,
    }
}

fn alg_lower(rust_ty: &str) -> &'static str {
    match rust_ty {
        "Md5" => "md5",
        "Sha1" => "sha1",
        "Sha224" => "sha224",
        "Sha256" => "sha256",
        "Sha384" => "sha384",
        "Sha512" => "sha512",
        "Sm3" => "sm3",
        "Sha3_224" => "sha3_224",
        "Sha3_256" => "sha3_256",
        "Sha3_384" => "sha3_384",
        "Sha3_512" => "sha3_512",
        _ => "unknown",
    }
}

fn write_header(out: &mut String, used_hashes: &BTreeSet<&'static str>) {
    out.push_str(
        "// This file is GENERATED by `cargo xtask migrate-c-tests --algo hmac`.\n\
         // DO NOT EDIT BY HAND. Source: openhitls C SDV test_suite_sdv_eal_mac_hmac.data\n\
         //\n\
         // Generator: docs/c-test-migration-plan.md Phase A (xtask).\n\n",
    );

    // File-level cfg: only build/run when every hash module touched by
    // the emitted tests is enabled. Always include `hmac` itself.
    let mut features: BTreeSet<&'static str> = BTreeSet::new();
    features.insert("hmac");
    for ty in used_hashes {
        features.insert(feature_for(ty));
    }
    let parts: Vec<String> = features
        .iter()
        .map(|f| format!("feature = \"{f}\""))
        .collect();
    writeln!(out, "#![cfg(all({}))]", parts.join(", ")).unwrap();
    out.push('\n');

    out.push_str("use hitls_crypto::hmac::Hmac;\n");
    out.push_str("use hitls_crypto::provider::Digest;\n");

    // Per-hash imports, grouped by source module.
    let mut sha2_imports: Vec<&str> = Vec::new();
    let mut sha3_imports: Vec<&str> = Vec::new();
    for ty in used_hashes {
        match feature_for(ty) {
            "sha2" => sha2_imports.push(ty),
            "sha3" => sha3_imports.push(ty),
            "md5" => out.push_str("use hitls_crypto::md5::Md5;\n"),
            "sha1" => out.push_str("use hitls_crypto::sha1::Sha1;\n"),
            "sm3" => out.push_str("use hitls_crypto::sm3::Sm3;\n"),
            _ => {}
        }
    }
    if !sha2_imports.is_empty() {
        writeln!(
            out,
            "use hitls_crypto::sha2::{{{}}};",
            sha2_imports.join(", ")
        )
        .unwrap();
    }
    if !sha3_imports.is_empty() {
        writeln!(
            out,
            "use hitls_crypto::sha3::{{{}}};",
            sha3_imports.join(", ")
        )
        .unwrap();
    }
    out.push('\n');
}

fn feature_for(rust_ty: &str) -> &'static str {
    match rust_ty {
        "Md5" => "md5",
        "Sha1" => "sha1",
        "Sha224" | "Sha256" | "Sha384" | "Sha512" => "sha2",
        "Sm3" => "sm3",
        "Sha3_224" | "Sha3_256" | "Sha3_384" | "Sha3_512" => "sha3",
        _ => "unknown",
    }
}

fn write_footer(out: &mut String, stats: &EmitStats, total: usize) {
    writeln!(
        out,
        "\n// Generation summary: {emitted} emitted / {api} API-surface skipped (N/A in Rust) \
         / {unk} unknown / {unsupported} unsupported alg (e.g. SHA-3) / {total} total C cases.",
        emitted = stats.emitted,
        api = stats.skipped_api,
        unk = stats.skipped_unknown,
        unsupported = stats.skipped_unsupported_alg,
        total = total,
    )
    .unwrap();
}

fn emit_one_shot(
    out: &mut String,
    case: &TestCase,
    stats: &mut EmitStats,
    used_hashes: &mut BTreeSet<&'static str>,
) {
    // Expected: 4 args = alg, key, msg, expected.
    if case.args.len() != 4 {
        stats.skipped_unknown += 1;
        return;
    }
    let Some(alg) = case.args[0].as_symbol() else {
        stats.skipped_unknown += 1;
        return;
    };
    let Some(key) = case.args[1].as_hex() else {
        stats.skipped_unknown += 1;
        return;
    };
    let Some(msg) = case.args[2].as_hex() else {
        stats.skipped_unknown += 1;
        return;
    };
    let Some(expected) = case.args[3].as_hex() else {
        stats.skipped_unknown += 1;
        return;
    };
    let Some((rust_ty, _feature)) = alg_to_rust(alg) else {
        stats.skipped_unsupported_alg += 1;
        return;
    };
    used_hashes.insert(rust_ty);

    let fn_name = format!("tc_line{}_hmac_{}_one_shot", case.line, alg_lower(rust_ty));
    write_test_doc(out, case);
    writeln!(out, "#[test]").unwrap();
    writeln!(out, "fn {fn_name}() {{").unwrap();
    writeln!(out, "    let key: &[u8] = {};", format_byte_slice(key)).unwrap();
    writeln!(out, "    let msg: &[u8] = {};", format_byte_slice(msg)).unwrap();
    writeln!(
        out,
        "    let expected: &[u8] = {};",
        format_byte_slice(expected)
    )
    .unwrap();
    writeln!(
        out,
        "    let factory = || -> Box<dyn Digest> {{ Box::new({rust_ty}::new()) }};"
    )
    .unwrap();
    writeln!(
        out,
        "    let actual = Hmac::mac(factory, key, msg).unwrap();"
    )
    .unwrap();
    writeln!(out, "    assert_eq!(actual.as_slice(), expected);").unwrap();
    writeln!(out, "}}\n").unwrap();
    stats.emitted += 1;
}

fn write_test_doc(out: &mut String, case: &TestCase) {
    if let Some(desc) = &case.description {
        writeln!(out, "/// {desc}").unwrap();
    }
    writeln!(
        out,
        "/// C source: {} (line {}, one-shot HMAC KAT)",
        case.tc_name, case.line
    )
    .unwrap();
}

// ---------------------------------------------------------------------------
// CMAC
// ---------------------------------------------------------------------------

/// CMAC `.data` rows that carry a real KAT (`alg : key : msg : expected`)
/// all use the `_FUN_TC004` suffix. Everything else — context lifecycle,
/// provider stubs, alignment probes — is API-surface that doesn't map to
/// the Rust API.
pub fn emit_cmac_kat(cases: &[TestCase]) -> (String, EmitStats) {
    let mut body = String::new();
    let mut stats = EmitStats::default();
    let mut used_sm4 = false;

    for case in cases {
        match classify_cmac(&case.tc_name) {
            CaseKind::OneShot => emit_cmac_one_shot(&mut body, case, &mut stats, &mut used_sm4),
            CaseKind::ApiSurface => stats.skipped_api += 1,
            CaseKind::Unknown => stats.skipped_unknown += 1,
        }
    }

    let mut out = String::new();
    write_cmac_header(&mut out, used_sm4);
    out.push_str(&body);
    write_footer(&mut out, &stats, cases.len());
    (out, stats)
}

fn classify_cmac(tc_name: &str) -> CaseKind {
    // Context-lifecycle and provider/stub patterns are not portable to Rust.
    if tc_name.contains("_API_TC")
        || tc_name.contains("_COPY_CTX_")
        || tc_name.contains("_DUP_CTX_")
        || tc_name.contains("_DEFAULT_PROVIDER_")
        || tc_name.contains("_STUB_TC")
        || tc_name.contains("_ADDR_NOT_ALIGN_")
    {
        return CaseKind::ApiSurface;
    }
    // FUN_TC004 is the only row shape carrying a 4-arg KAT.
    // FUN_TC001/002/003/005/006 are workflow / repetition-count tests.
    if tc_name.contains("_FUN_TC004") {
        CaseKind::OneShot
    } else if tc_name.contains("_FUN_TC") {
        CaseKind::ApiSurface
    } else {
        CaseKind::Unknown
    }
}

/// Map a CMAC algorithm symbol to (short label, cipher kind).
fn cmac_alg(symbol: &str) -> Option<(&'static str, CmacCipher)> {
    match symbol {
        "CRYPT_MAC_CMAC_AES128" => Some(("aes128", CmacCipher::Aes)),
        "CRYPT_MAC_CMAC_AES192" => Some(("aes192", CmacCipher::Aes)),
        "CRYPT_MAC_CMAC_AES256" => Some(("aes256", CmacCipher::Aes)),
        "CRYPT_MAC_CMAC_SM4" => Some(("sm4", CmacCipher::Sm4)),
        _ => None,
    }
}

#[derive(Clone, Copy)]
enum CmacCipher {
    Aes,
    Sm4,
}

fn write_cmac_header(out: &mut String, used_sm4: bool) {
    out.push_str(
        "// This file is GENERATED by `cargo xtask migrate-c-tests --algo cmac`.\n\
         // DO NOT EDIT BY HAND. Source: openhitls C SDV test_suite_sdv_eal_mac_cmac.data\n\
         //\n\
         // Generator: docs/c-test-migration-plan.md Phase A (xtask).\n\n",
    );
    if used_sm4 {
        out.push_str("#![cfg(all(feature = \"cmac\", feature = \"aes\", feature = \"sm4\"))]\n\n");
        out.push_str("use hitls_crypto::cmac::{Cmac, CmacSm4};\n\n");
    } else {
        out.push_str("#![cfg(all(feature = \"cmac\", feature = \"aes\"))]\n\n");
        out.push_str("use hitls_crypto::cmac::Cmac;\n\n");
    }
}

fn emit_cmac_one_shot(
    out: &mut String,
    case: &TestCase,
    stats: &mut EmitStats,
    used_sm4: &mut bool,
) {
    // Expected: 4 args = alg, key, msg, expected.
    if case.args.len() != 4 {
        stats.skipped_unknown += 1;
        return;
    }
    let Some(alg) = case.args[0].as_symbol() else {
        stats.skipped_unknown += 1;
        return;
    };
    let Some(key) = case.args[1].as_hex() else {
        stats.skipped_unknown += 1;
        return;
    };
    let Some(msg) = case.args[2].as_hex() else {
        stats.skipped_unknown += 1;
        return;
    };
    let Some(expected) = case.args[3].as_hex() else {
        stats.skipped_unknown += 1;
        return;
    };
    let Some((label, cipher)) = cmac_alg(alg) else {
        stats.skipped_unsupported_alg += 1;
        return;
    };
    let cmac_ty = match cipher {
        CmacCipher::Aes => "Cmac",
        CmacCipher::Sm4 => {
            *used_sm4 = true;
            "CmacSm4"
        }
    };

    let fn_name = format!("tc_line{}_cmac_{}_one_shot", case.line, label);
    write_cmac_test_doc(out, case);
    writeln!(out, "#[test]").unwrap();
    writeln!(out, "fn {fn_name}() {{").unwrap();
    writeln!(out, "    let key: &[u8] = {};", format_byte_slice(key)).unwrap();
    writeln!(out, "    let msg: &[u8] = {};", format_byte_slice(msg)).unwrap();
    writeln!(
        out,
        "    let expected: &[u8] = {};",
        format_byte_slice(expected)
    )
    .unwrap();
    writeln!(out, "    let mut cmac = {cmac_ty}::new(key).unwrap();").unwrap();
    writeln!(out, "    cmac.update(msg).unwrap();").unwrap();
    writeln!(out, "    let mut actual = [0u8; 16];").unwrap();
    writeln!(out, "    cmac.finish(&mut actual).unwrap();").unwrap();
    writeln!(out, "    assert_eq!(actual.as_slice(), expected);").unwrap();
    writeln!(out, "}}\n").unwrap();
    stats.emitted += 1;
}

fn write_cmac_test_doc(out: &mut String, case: &TestCase) {
    if let Some(desc) = &case.description {
        writeln!(out, "/// {desc}").unwrap();
    }
    writeln!(
        out,
        "/// C source: {} (line {}, one-shot CMAC KAT)",
        case.tc_name, case.line
    )
    .unwrap();
}
