use std::collections::BTreeSet;
use std::fmt::Write;

use crate::digest::EmitStats;
use crate::parser::{format_byte_slice, TestCase};

pub fn emit_hmac_kat(cases: &[TestCase]) -> (String, EmitStats) {
    let mut body = String::new();
    let mut stats = EmitStats::default();
    let mut used_hashes: BTreeSet<&'static str> = BTreeSet::new();

    for case in cases {
        let kind = classify(&case.tc_name);
        match kind {
            CaseKind::OneShot => {
                emit_one_shot(&mut body, case, &mut stats, &mut used_hashes);
            }
            CaseKind::ApiSurface => stats.skipped_api += 1,
            CaseKind::Unknown => stats.skipped_unknown += 1,
        }
    }

    let mut out = String::new();
    write_header(&mut out, &used_hashes);
    out.push_str(&body);
    write_footer(&mut out, &stats, cases.len());
    (out, stats)
}

#[derive(Debug, Clone, Copy)]
enum CaseKind {
    /// FUN_TC001: alg + key + msg + expected (one-shot HMAC KAT).
    OneShot,
    /// API_*, COPY_CTX_*, DUP_CTX_*, DEFAULT_PROVIDER_*, FUN_TC002/3 (split + ctx-reuse).
    ApiSurface,
    Unknown,
}

fn classify(tc_name: &str) -> CaseKind {
    // Architectural / context-lifecycle patterns first.
    if tc_name.contains("_API_TC")
        || tc_name.contains("_COPY_CTX_")
        || tc_name.contains("_DUP_CTX_")
        || tc_name.contains("_DEFAULT_PROVIDER_")
        || tc_name.contains("_FUN_TC002")
        || tc_name.contains("_FUN_TC003")
    {
        return CaseKind::ApiSurface;
    }
    if tc_name.contains("_FUN_TC001") {
        CaseKind::OneShot
    } else {
        CaseKind::Unknown
    }
}

/// Map C HMAC algorithm symbol to (Rust hash type, feature name).
/// Returns `None` for symbols whose Rust counterpart doesn't implement
/// `provider::Digest` (currently SHA-3 variants).
fn alg_to_rust(symbol: &str) -> Option<(&'static str, &'static str)> {
    match symbol {
        "CRYPT_MAC_HMAC_MD5" => Some(("Md5", "md5")),
        "CRYPT_MAC_HMAC_SHA1" => Some(("Sha1", "sha1")),
        "CRYPT_MAC_HMAC_SHA224" => Some(("Sha224", "sha2")),
        "CRYPT_MAC_HMAC_SHA256" => Some(("Sha256", "sha2")),
        "CRYPT_MAC_HMAC_SHA384" => Some(("Sha384", "sha2")),
        "CRYPT_MAC_HMAC_SHA512" => Some(("Sha512", "sha2")),
        "CRYPT_MAC_HMAC_SM3" => Some(("Sm3", "sm3")),
        // SHA-3 variants: Rust port doesn't yet impl `Digest` for Sha3_*.
        "CRYPT_MAC_HMAC_SHA3_224"
        | "CRYPT_MAC_HMAC_SHA3_256"
        | "CRYPT_MAC_HMAC_SHA3_384"
        | "CRYPT_MAC_HMAC_SHA3_512" => None,
        _ => None,
    }
}

fn alg_lower(rust_ty: &str) -> &'static str {
    match rust_ty {
        "Md5" => "md5",
        "Sha1" => "sha1",
        "Sha224" => "sha224",
        "Sha256" => "sha256",
        "Sha384" => "sha384",
        "Sha512" => "sha512",
        "Sm3" => "sm3",
        _ => "unknown",
    }
}

fn write_header(out: &mut String, used_hashes: &BTreeSet<&'static str>) {
    out.push_str(
        "// This file is GENERATED by `cargo xtask migrate-c-tests --algo hmac`.\n\
         // DO NOT EDIT BY HAND. Source: openhitls C SDV test_suite_sdv_eal_mac_hmac.data\n\
         //\n\
         // Generator: docs/c-test-migration-plan.md Phase A (xtask).\n\n",
    );

    // File-level cfg: only build/run when every hash module touched by
    // the emitted tests is enabled. Always include `hmac` itself.
    let mut features: BTreeSet<&'static str> = BTreeSet::new();
    features.insert("hmac");
    for ty in used_hashes {
        features.insert(feature_for(ty));
    }
    let parts: Vec<String> = features
        .iter()
        .map(|f| format!("feature = \"{f}\""))
        .collect();
    writeln!(out, "#![cfg(all({}))]", parts.join(", ")).unwrap();
    out.push('\n');

    out.push_str("use hitls_crypto::hmac::Hmac;\n");
    out.push_str("use hitls_crypto::provider::Digest;\n");

    // Per-hash imports, grouped by source module.
    let mut sha2_imports: Vec<&str> = Vec::new();
    for ty in used_hashes {
        match feature_for(ty) {
            "sha2" => sha2_imports.push(ty),
            "md5" => out.push_str("use hitls_crypto::md5::Md5;\n"),
            "sha1" => out.push_str("use hitls_crypto::sha1::Sha1;\n"),
            "sm3" => out.push_str("use hitls_crypto::sm3::Sm3;\n"),
            _ => {}
        }
    }
    if !sha2_imports.is_empty() {
        writeln!(
            out,
            "use hitls_crypto::sha2::{{{}}};",
            sha2_imports.join(", ")
        )
        .unwrap();
    }
    out.push('\n');
}

fn feature_for(rust_ty: &str) -> &'static str {
    match rust_ty {
        "Md5" => "md5",
        "Sha1" => "sha1",
        "Sha224" | "Sha256" | "Sha384" | "Sha512" => "sha2",
        "Sm3" => "sm3",
        _ => "unknown",
    }
}

fn write_footer(out: &mut String, stats: &EmitStats, total: usize) {
    writeln!(
        out,
        "\n// Generation summary: {emitted} emitted / {api} API-surface skipped (N/A in Rust) \
         / {unk} unknown / {unsupported} unsupported alg (e.g. SHA-3) / {total} total C cases.",
        emitted = stats.emitted,
        api = stats.skipped_api,
        unk = stats.skipped_unknown,
        unsupported = stats.skipped_unsupported_alg,
        total = total,
    )
    .unwrap();
}

fn emit_one_shot(
    out: &mut String,
    case: &TestCase,
    stats: &mut EmitStats,
    used_hashes: &mut BTreeSet<&'static str>,
) {
    // Expected: 4 args = alg, key, msg, expected.
    if case.args.len() != 4 {
        stats.skipped_unknown += 1;
        return;
    }
    let Some(alg) = case.args[0].as_symbol() else {
        stats.skipped_unknown += 1;
        return;
    };
    let Some(key) = case.args[1].as_hex() else {
        stats.skipped_unknown += 1;
        return;
    };
    let Some(msg) = case.args[2].as_hex() else {
        stats.skipped_unknown += 1;
        return;
    };
    let Some(expected) = case.args[3].as_hex() else {
        stats.skipped_unknown += 1;
        return;
    };
    let Some((rust_ty, _feature)) = alg_to_rust(alg) else {
        stats.skipped_unsupported_alg += 1;
        return;
    };
    used_hashes.insert(rust_ty);

    let fn_name = format!("tc_line{}_hmac_{}_one_shot", case.line, alg_lower(rust_ty));
    write_test_doc(out, case);
    writeln!(out, "#[test]").unwrap();
    writeln!(out, "fn {fn_name}() {{").unwrap();
    writeln!(out, "    let key: &[u8] = {};", format_byte_slice(key)).unwrap();
    writeln!(out, "    let msg: &[u8] = {};", format_byte_slice(msg)).unwrap();
    writeln!(
        out,
        "    let expected: &[u8] = {};",
        format_byte_slice(expected)
    )
    .unwrap();
    writeln!(
        out,
        "    let factory = || -> Box<dyn Digest> {{ Box::new({rust_ty}::new()) }};"
    )
    .unwrap();
    writeln!(
        out,
        "    let actual = Hmac::mac(factory, key, msg).unwrap();"
    )
    .unwrap();
    writeln!(out, "    assert_eq!(actual.as_slice(), expected);").unwrap();
    writeln!(out, "}}\n").unwrap();
    stats.emitted += 1;
}

fn write_test_doc(out: &mut String, case: &TestCase) {
    if let Some(desc) = &case.description {
        writeln!(out, "/// {desc}").unwrap();
    }
    writeln!(
        out,
        "/// C source: {} (line {}, one-shot HMAC KAT)",
        case.tc_name, case.line
    )
    .unwrap();
}
