//! Emitter for openHiTLS C `test_suite_sdv_mlkem.data` — ML-KEM (FIPS 203).
//!
//! Migrates the **decapsulation** side of the KAT family
//! `MLKEM_ENCAPS_DECAPS_FUNC_TC001` (`bits : m : EK : DK : CT : SK :
//! isProvider`). Decapsulation is deterministic — given the decap key `DK` and
//! a ciphertext `CT`, FIPS 203 fixes the shared secret `SK` — so it maps
//! cleanly onto `MlKemKeyPair::from_decapsulation_key(bits, DK).decapsulate(CT)`
//! and is checked byte-for-byte against `SK`.
//!
//! The *encapsulation* side of the same vector (and `KEYGEN_FUNC_TC001`) needs
//! the C test's injected `m` / `(z,d)` randomness, which the Rust port draws
//! from the system RNG with no public injection hook, so those are not emitted
//! here (the deterministic hooks are crate-private to avoid a public
//! misuse-of-randomness footgun). API-surface CRUD rows are routed to
//! `ApiSurface`.

use std::fmt::Write;

use crate::digest::EmitStats;
use crate::parser::{format_byte_slice, TestCase};

pub fn emit_mlkem_kat(cases: &[TestCase]) -> (String, EmitStats) {
    let mut body = String::new();
    let mut stats = EmitStats::default();

    for case in cases {
        match classify(&case.tc_name) {
            Kind::EncapsDecaps => emit_decaps(&mut body, case, &mut stats),
            Kind::ApiSurface => stats.skipped_api += 1,
            Kind::Unknown => stats.skipped_unknown += 1,
        }
    }

    let mut out = String::new();
    write_header(&mut out);
    out.push_str(&body);
    write_footer(&mut out, &stats, cases.len());
    (out, stats)
}

#[derive(Debug, Clone, Copy)]
enum Kind {
    EncapsDecaps,
    ApiSurface,
    Unknown,
}

fn classify(tc: &str) -> Kind {
    if tc.contains("MLKEM_ENCAPS_DECAPS_FUNC_TC001") {
        return Kind::EncapsDecaps;
    }
    // Keygen-from-seed and encaps-from-m need randomness injection; key
    // setters/getters, ctrl, keycmp are EAL CRUD.
    if tc.contains("MLKEM_KEYGEN")
        || tc.contains("MLKEM_KEYCMP")
        || tc.contains("_API_")
        || tc.contains("MLKEM_SETPUB")
        || tc.contains("MLKEM_SETPRV")
    {
        return Kind::ApiSurface;
    }
    Kind::Unknown
}

/// Skip provider-flag duplicates: the rightmost arg `1` is the EAL provider
/// copy of an otherwise byte-identical row. Rust has no provider concept.
fn skip_if_provider_dup(case: &TestCase) -> bool {
    matches!(case.args.last().and_then(|a| a.as_symbol()), Some("1"))
}

/// Map the C `CRYPT_KEM_TYPE_MLKEM_*` symbol to the Rust parameter-set id.
fn type_to_param(symbol: &str) -> Option<u32> {
    match symbol {
        "CRYPT_KEM_TYPE_MLKEM_512" => Some(512),
        "CRYPT_KEM_TYPE_MLKEM_768" => Some(768),
        "CRYPT_KEM_TYPE_MLKEM_1024" => Some(1024),
        _ => None,
    }
}

fn emit_decaps(out: &mut String, case: &TestCase, stats: &mut EmitStats) {
    if skip_if_provider_dup(case) {
        stats.skipped_api += 1;
        return;
    }
    // Shape: bits : m : EK : DK : CT : SK : isProvider
    if case.args.len() < 6 {
        stats.skipped_unknown += 1;
        return;
    }
    let Some(param) = case.args[0].as_symbol().and_then(type_to_param) else {
        stats.skipped_unsupported_alg += 1;
        return;
    };
    // args[1] = m (encaps randomness, unused for decaps), args[2] = EK (unused)
    let (Some(dk), Some(ct), Some(sk)) = (
        case.args[3].as_hex(),
        case.args[4].as_hex(),
        case.args[5].as_hex(),
    ) else {
        stats.skipped_unknown += 1;
        return;
    };

    let fn_name = format!("tc_line{}_mlkem{}_decaps", case.line, param);
    write_doc(out, case, param);
    writeln!(out, "#[test]").unwrap();
    writeln!(out, "fn {fn_name}() {{").unwrap();
    writeln!(out, "    let dk: &[u8] = {};", format_byte_slice(dk)).unwrap();
    writeln!(out, "    let ct: &[u8] = {};", format_byte_slice(ct)).unwrap();
    writeln!(out, "    let sk: &[u8] = {};", format_byte_slice(sk)).unwrap();
    writeln!(
        out,
        "    let kp = MlKemKeyPair::from_decapsulation_key({param}, dk).unwrap();"
    )
    .unwrap();
    writeln!(out, "    assert_eq!(kp.decapsulate(ct).unwrap(), sk);").unwrap();
    writeln!(out, "}}\n").unwrap();
    stats.emitted += 1;
}

fn write_header(out: &mut String) {
    out.push_str(
        "// This file is GENERATED by `cargo xtask migrate-c-tests --algo mlkem`.\n\
         // DO NOT EDIT BY HAND. Source: openhitls C SDV test_suite_sdv_mlkem.data\n\
         //\n\
         // Generator: docs/c-test-migration-plan.md Phase A (xtask).\n\n",
    );
    out.push_str("#![cfg(feature = \"mlkem\")]\n\n");
    out.push_str("use hitls_crypto::mlkem::MlKemKeyPair;\n\n");
}

fn write_footer(out: &mut String, stats: &EmitStats, total: usize) {
    writeln!(
        out,
        "\n// Generation summary: {emitted} emitted / {api} API-surface skipped \
         / {unk} unknown / {unsupported} unsupported alg / {total} total C cases.",
        emitted = stats.emitted,
        api = stats.skipped_api,
        unk = stats.skipped_unknown,
        unsupported = stats.skipped_unsupported_alg,
        total = total,
    )
    .unwrap();
}

fn write_doc(out: &mut String, case: &TestCase, param: u32) {
    if let Some(desc) = &case.description {
        writeln!(out, "/// {desc}").unwrap();
    }
    writeln!(
        out,
        "/// C source: {} (line {}, ML-KEM-{param} decapsulation KAT)",
        case.tc_name, case.line
    )
    .unwrap();
}
