//! Phase J-1 — HOTP (RFC 4226) / TOTP (RFC 6238) OTP KAT emitter.
//!
//! Source: openHiTLS C SDV `auth/otp/test_suite_sdv_otp.data`.
//!
//! The C `.data` rows publish RFC 4226 Appendix D (HOTP, SHA-1) and RFC 6238
//! Appendix B (TOTP, SHA-1/256/512) known-answer vectors, plus validate-side
//! success / mismatch rows. We migrate the deterministic families:
//!
//! - `GEN_HOTP_API_TC001`  — `Hotp::generate(counter)` byte-exact
//! - `GEN_TOTP_API_TC001`  — `Totp::generate(timestamp)` byte-exact (period 30)
//! - `GEN_TOTP_API_TC002`  — `Totp::generate` with custom start offset + step
//! - `VALIDATE_HOTP_API_TC001` — `Hotp::verify` success/mismatch
//! - `VALIDATE_TOTP_API_TC002` — `Totp::verify` with the validWindow carried
//!   in the data row (window == 0)
//!
//! Routed to API-surface (counted, not migrated):
//! - `VALIDATE_TOTP_API_TC001` — the C ctx supplies a *default* validWindow
//!   that is **not present in the data row** (so several rows accept
//!   window-adjacent OTPs). A faithful byte-exact migration cannot hardcode a
//!   magic window absent from the vector; the generate side
//!   (`GEN_TOTP_API_TC001`) already pins the exact crypto for these times.
//! - `INIT_API` / `SET_CRYPTO_CB_API` / `CTX_CTRL_API` — EAL ctx CRUD with no
//!   Rust runtime counterpart.

use std::fmt::Write;

use crate::digest::EmitStats;
use crate::parser::{format_byte_slice, Arg, TestCase};

pub fn emit_otp_kat(cases: &[TestCase]) -> (String, EmitStats) {
    let mut body = String::new();
    let mut stats = EmitStats::default();

    for case in cases {
        match classify(&case.tc_name) {
            CaseKind::HotpGen => emit_hotp_gen(&mut body, case, &mut stats),
            CaseKind::TotpGen => emit_totp_gen(&mut body, case, &mut stats),
            CaseKind::HotpValidate => emit_hotp_validate(&mut body, case, &mut stats),
            CaseKind::TotpValidate => emit_totp_validate(&mut body, case, &mut stats),
            CaseKind::ApiSurface => stats.skipped_api += 1,
            CaseKind::Unknown => stats.skipped_unknown += 1,
        }
    }

    let mut out = String::new();
    write_header(&mut out);
    out.push_str(&body);
    write_footer(&mut out, &stats, cases.len());
    (out, stats)
}

#[derive(Debug, Clone, Copy)]
enum CaseKind {
    HotpGen,
    TotpGen,
    HotpValidate,
    /// Only `VALIDATE_TOTP_API_TC002` (validWindow in the row) is migratable.
    TotpValidate,
    ApiSurface,
    Unknown,
}

fn classify(tc_name: &str) -> CaseKind {
    if tc_name.contains("GEN_HOTP_API_TC001") {
        CaseKind::HotpGen
    } else if tc_name.contains("GEN_TOTP_API_TC001") || tc_name.contains("GEN_TOTP_API_TC002") {
        CaseKind::TotpGen
    } else if tc_name.contains("VALIDATE_HOTP_API_TC001") {
        CaseKind::HotpValidate
    } else if tc_name.contains("VALIDATE_TOTP_API_TC002") {
        CaseKind::TotpValidate
    } else if tc_name.contains("VALIDATE_TOTP_API_TC001")
        || tc_name.contains("_INIT_API")
        || tc_name.contains("_SET_CRYPTO_CB_API")
        || tc_name.contains("_CTX_CTRL_API")
    {
        CaseKind::ApiSurface
    } else {
        CaseKind::Unknown
    }
}

/// Map a C OTP hash symbol to the Rust `OtpHashAlg` variant.
fn alg_to_rust(symbol: &str) -> Option<&'static str> {
    match symbol {
        "HITLS_AUTH_OTP_CRYPTO_SHA1" => Some("Sha1"),
        "HITLS_AUTH_OTP_CRYPTO_SHA256" => Some("Sha256"),
        "HITLS_AUTH_OTP_CRYPTO_SHA512" => Some("Sha512"),
        _ => None,
    }
}

/// Fold a big-endian byte slice into a `u64` (used for the 8-byte time /
/// start-offset counters the C `.data` carries as quoted hex).
fn hex_be_to_u64(bytes: &[u8]) -> u64 {
    let mut v = 0u64;
    for &b in bytes {
        v = (v << 8) | u64::from(b);
    }
    v
}

/// Recover a decimal OTP value from an `Arg` the parser stored as `Arg::Hex`.
///
/// The C `.data` quotes the expected OTP as a *decimal* string (`"755224"`),
/// but the xtask parser sees a valid even-length hex literal and decodes it to
/// bytes. Re-encoding those bytes as lowercase hex reproduces the original
/// decimal digits exactly (every nibble was a decimal digit 0-9), which we
/// then parse as the `u32` OTP value the Rust API returns.
fn otp_decimal(arg: &Arg) -> Option<u32> {
    let bytes = arg.as_hex()?;
    let s: String = bytes.iter().map(|b| format!("{b:02x}")).collect();
    s.parse::<u32>().ok()
}

/// A `Symbol` integer field (`count` / `digits` / `timeStepSize` / window).
fn sym_u64(arg: &Arg) -> Option<u64> {
    arg.as_symbol()?.parse::<u64>().ok()
}

fn write_header(out: &mut String) {
    out.push_str(
        "// This file is GENERATED by `cargo xtask migrate-c-tests --algo otp`.\n\
         // DO NOT EDIT BY HAND. Source: openhitls C SDV auth/otp/test_suite_sdv_otp.data\n\
         //\n\
         // Generator: docs/issue-42-phase-jklm-plan.md Phase J-1 (xtask).\n\n",
    );
    out.push_str("#![cfg(feature = \"otp\")]\n\n");
    out.push_str("use hitls_auth::otp::{Hotp, OtpHashAlg, Totp};\n\n");
}

fn write_footer(out: &mut String, stats: &EmitStats, total: usize) {
    writeln!(
        out,
        "\n// Generation summary: {emitted} emitted / {api} API-surface skipped (N/A in Rust) \
         / {unk} unknown / {total} total C cases.",
        emitted = stats.emitted,
        api = stats.skipped_api,
        unk = stats.skipped_unknown,
        total = total,
    )
    .unwrap();
}

fn write_test_doc(out: &mut String, case: &TestCase, note: &str) {
    if let Some(desc) = &case.description {
        writeln!(out, "/// {desc}").unwrap();
    }
    writeln!(
        out,
        "/// C source: {} (line {}, {note})",
        case.tc_name, case.line
    )
    .unwrap();
}

/// `count : key : digits : alg : expectedOtp`
fn emit_hotp_gen(out: &mut String, case: &TestCase, stats: &mut EmitStats) {
    if case.args.len() != 5 {
        stats.skipped_unknown += 1;
        return;
    }
    let (Some(count), Some(key), Some(digits), Some(alg_sym), Some(expected)) = (
        sym_u64(&case.args[0]),
        case.args[1].as_hex(),
        sym_u64(&case.args[2]),
        case.args[3].as_symbol(),
        otp_decimal(&case.args[4]),
    ) else {
        stats.skipped_unknown += 1;
        return;
    };
    let Some(alg) = alg_to_rust(alg_sym) else {
        stats.skipped_unknown += 1;
        return;
    };

    write_test_doc(out, case, "HOTP generate KAT (RFC 4226)");
    writeln!(out, "#[test]").unwrap();
    writeln!(out, "fn tc_line{}_hotp_gen() {{", case.line).unwrap();
    writeln!(out, "    let secret: &[u8] = {};", format_byte_slice(key)).unwrap();
    writeln!(
        out,
        "    let hotp = Hotp::with_hash(secret, {digits}, OtpHashAlg::{alg});"
    )
    .unwrap();
    writeln!(
        out,
        "    assert_eq!(hotp.generate({count}).unwrap(), {expected});"
    )
    .unwrap();
    writeln!(out, "}}\n").unwrap();
    stats.emitted += 1;
}

/// TC001: `curTime : key : digits : alg : expectedOtp` (period 30)
/// TC002: `curTime : key : digits : alg : startOffset : timeStep : expectedOtp`
fn emit_totp_gen(out: &mut String, case: &TestCase, stats: &mut EmitStats) {
    let is_tc002 = case.tc_name.contains("TC002");
    let want = if is_tc002 { 7 } else { 5 };
    if case.args.len() != want {
        stats.skipped_unknown += 1;
        return;
    }
    let Some(key) = case.args[1].as_hex() else {
        stats.skipped_unknown += 1;
        return;
    };
    let (Some(cur_time), Some(digits), Some(alg_sym)) = (
        case.args[0].as_hex().map(hex_be_to_u64),
        sym_u64(&case.args[2]),
        case.args[3].as_symbol(),
    ) else {
        stats.skipped_unknown += 1;
        return;
    };
    let Some(alg) = alg_to_rust(alg_sym) else {
        stats.skipped_unknown += 1;
        return;
    };

    // (period, timestamp-fed-to-generate). The Rust `Totp::generate` computes
    // counter = timestamp / period; the C moving factor is
    // (curTime - startOffset) / timeStep, so we fold startOffset into the
    // timestamp argument.
    let (period, timestamp, expected_idx) = if is_tc002 {
        let (Some(start), Some(step)) = (
            case.args[4].as_hex().map(hex_be_to_u64),
            sym_u64(&case.args[5]),
        ) else {
            stats.skipped_unknown += 1;
            return;
        };
        (step, cur_time - start, 6)
    } else {
        (30u64, cur_time, 4)
    };
    let Some(expected) = otp_decimal(&case.args[expected_idx]) else {
        stats.skipped_unknown += 1;
        return;
    };

    write_test_doc(out, case, "TOTP generate KAT (RFC 6238)");
    writeln!(out, "#[test]").unwrap();
    writeln!(out, "fn tc_line{}_totp_gen() {{", case.line).unwrap();
    writeln!(out, "    let secret: &[u8] = {};", format_byte_slice(key)).unwrap();
    writeln!(
        out,
        "    let totp = Totp::with_hash(secret, {digits}, {period}, OtpHashAlg::{alg});"
    )
    .unwrap();
    writeln!(
        out,
        "    assert_eq!(totp.generate({timestamp}).unwrap(), {expected});"
    )
    .unwrap();
    writeln!(out, "}}\n").unwrap();
    stats.emitted += 1;
}

/// `count : key : digits : alg : otp : expectRes`
fn emit_hotp_validate(out: &mut String, case: &TestCase, stats: &mut EmitStats) {
    if case.args.len() != 6 {
        stats.skipped_unknown += 1;
        return;
    }
    let (Some(count), Some(key), Some(digits), Some(alg_sym), Some(otp), Some(res)) = (
        sym_u64(&case.args[0]),
        case.args[1].as_hex(),
        sym_u64(&case.args[2]),
        case.args[3].as_symbol(),
        otp_decimal(&case.args[4]),
        case.args[5].as_symbol(),
    ) else {
        stats.skipped_unknown += 1;
        return;
    };
    let (Some(alg), Some(expect)) = (alg_to_rust(alg_sym), expect_bool(res)) else {
        stats.skipped_unknown += 1;
        return;
    };

    write_test_doc(out, case, "HOTP validate (RFC 4226)");
    writeln!(out, "#[test]").unwrap();
    writeln!(out, "fn tc_line{}_hotp_validate() {{", case.line).unwrap();
    writeln!(out, "    let secret: &[u8] = {};", format_byte_slice(key)).unwrap();
    writeln!(
        out,
        "    let hotp = Hotp::with_hash(secret, {digits}, OtpHashAlg::{alg});"
    )
    .unwrap();
    let neg = if expect { "" } else { "!" };
    writeln!(
        out,
        "    assert!({neg}hotp.verify({otp}, {count}).unwrap());"
    )
    .unwrap();
    writeln!(out, "}}\n").unwrap();
    stats.emitted += 1;
}

/// `curTime : key : digits : alg : startOffset : timeStep : validWindow : otp : expectRes`
fn emit_totp_validate(out: &mut String, case: &TestCase, stats: &mut EmitStats) {
    if case.args.len() != 9 {
        stats.skipped_unknown += 1;
        return;
    }
    let Some(key) = case.args[1].as_hex() else {
        stats.skipped_unknown += 1;
        return;
    };
    let (
        Some(cur_time),
        Some(digits),
        Some(alg_sym),
        Some(start),
        Some(step),
        Some(window),
        Some(otp),
        Some(res),
    ) = (
        case.args[0].as_hex().map(hex_be_to_u64),
        sym_u64(&case.args[2]),
        case.args[3].as_symbol(),
        case.args[4].as_hex().map(hex_be_to_u64),
        sym_u64(&case.args[5]),
        sym_u64(&case.args[6]),
        otp_decimal(&case.args[7]),
        case.args[8].as_symbol(),
    )
    else {
        stats.skipped_unknown += 1;
        return;
    };
    let (Some(alg), Some(expect)) = (alg_to_rust(alg_sym), expect_bool(res)) else {
        stats.skipped_unknown += 1;
        return;
    };
    let timestamp = cur_time - start;

    write_test_doc(out, case, "TOTP validate (RFC 6238, validWindow in row)");
    writeln!(out, "#[test]").unwrap();
    writeln!(out, "fn tc_line{}_totp_validate() {{", case.line).unwrap();
    writeln!(out, "    let secret: &[u8] = {};", format_byte_slice(key)).unwrap();
    writeln!(
        out,
        "    let totp = Totp::with_hash(secret, {digits}, {step}, OtpHashAlg::{alg});"
    )
    .unwrap();
    let neg = if expect { "" } else { "!" };
    writeln!(
        out,
        "    assert!({neg}totp.verify({otp}, {timestamp}, {window}).unwrap());"
    )
    .unwrap();
    writeln!(out, "}}\n").unwrap();
    stats.emitted += 1;
}

/// C result symbol → expected Rust `verify` boolean.
fn expect_bool(res: &str) -> Option<bool> {
    match res {
        "HITLS_AUTH_SUCCESS" => Some(true),
        "HITLS_AUTH_OTP_VALIDATE_MISMATCH" => Some(false),
        _ => None,
    }
}
