// This file is GENERATED by `cargo xtask migrate-c-tests --algo otp`.
// DO NOT EDIT BY HAND. Source: openhitls C SDV auth/otp/test_suite_sdv_otp.data
//
// Generator: docs/issue-42-phase-jklm-plan.md Phase J-1 (xtask).

#![cfg(feature = "otp")]

use hitls_auth::otp::{Hotp, OtpHashAlg, Totp};

/// SDV_AUTH_OTP_GEN_HOTP_API_TC001 HOTP 0 #from RFC4226
/// C source: SDV_AUTH_OTP_GEN_HOTP_API_TC001 (line 22, HOTP generate KAT (RFC 4226))
#[test]
fn tc_line22_hotp_gen() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let hotp = Hotp::with_hash(secret, 6, OtpHashAlg::Sha1);
    assert_eq!(hotp.generate(0).unwrap(), 755224);
}

/// SDV_AUTH_OTP_GEN_HOTP_API_TC001 HOTP 1 #from RFC4226
/// C source: SDV_AUTH_OTP_GEN_HOTP_API_TC001 (line 24, HOTP generate KAT (RFC 4226))
#[test]
fn tc_line24_hotp_gen() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let hotp = Hotp::with_hash(secret, 6, OtpHashAlg::Sha1);
    assert_eq!(hotp.generate(1).unwrap(), 287082);
}

/// SDV_AUTH_OTP_GEN_HOTP_API_TC001 HOTP 2 #from RFC4226
/// C source: SDV_AUTH_OTP_GEN_HOTP_API_TC001 (line 26, HOTP generate KAT (RFC 4226))
#[test]
fn tc_line26_hotp_gen() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let hotp = Hotp::with_hash(secret, 6, OtpHashAlg::Sha1);
    assert_eq!(hotp.generate(2).unwrap(), 359152);
}

/// SDV_AUTH_OTP_GEN_HOTP_API_TC001 HOTP 3 #from RFC4226
/// C source: SDV_AUTH_OTP_GEN_HOTP_API_TC001 (line 28, HOTP generate KAT (RFC 4226))
#[test]
fn tc_line28_hotp_gen() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let hotp = Hotp::with_hash(secret, 6, OtpHashAlg::Sha1);
    assert_eq!(hotp.generate(3).unwrap(), 969429);
}

/// SDV_AUTH_OTP_GEN_HOTP_API_TC001 HOTP 4 #from RFC4226
/// C source: SDV_AUTH_OTP_GEN_HOTP_API_TC001 (line 30, HOTP generate KAT (RFC 4226))
#[test]
fn tc_line30_hotp_gen() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let hotp = Hotp::with_hash(secret, 6, OtpHashAlg::Sha1);
    assert_eq!(hotp.generate(4).unwrap(), 338314);
}

/// SDV_AUTH_OTP_GEN_HOTP_API_TC001 HOTP 5 #from RFC4226
/// C source: SDV_AUTH_OTP_GEN_HOTP_API_TC001 (line 32, HOTP generate KAT (RFC 4226))
#[test]
fn tc_line32_hotp_gen() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let hotp = Hotp::with_hash(secret, 6, OtpHashAlg::Sha1);
    assert_eq!(hotp.generate(5).unwrap(), 254676);
}

/// SDV_AUTH_OTP_GEN_HOTP_API_TC001 HOTP 6 #from RFC4226
/// C source: SDV_AUTH_OTP_GEN_HOTP_API_TC001 (line 34, HOTP generate KAT (RFC 4226))
#[test]
fn tc_line34_hotp_gen() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let hotp = Hotp::with_hash(secret, 6, OtpHashAlg::Sha1);
    assert_eq!(hotp.generate(6).unwrap(), 287922);
}

/// SDV_AUTH_OTP_GEN_HOTP_API_TC001 HOTP 7 #from RFC4226
/// C source: SDV_AUTH_OTP_GEN_HOTP_API_TC001 (line 36, HOTP generate KAT (RFC 4226))
#[test]
fn tc_line36_hotp_gen() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let hotp = Hotp::with_hash(secret, 6, OtpHashAlg::Sha1);
    assert_eq!(hotp.generate(7).unwrap(), 162583);
}

/// SDV_AUTH_OTP_GEN_HOTP_API_TC001 HOTP 8 #from RFC4226
/// C source: SDV_AUTH_OTP_GEN_HOTP_API_TC001 (line 38, HOTP generate KAT (RFC 4226))
#[test]
fn tc_line38_hotp_gen() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let hotp = Hotp::with_hash(secret, 6, OtpHashAlg::Sha1);
    assert_eq!(hotp.generate(8).unwrap(), 399871);
}

/// SDV_AUTH_OTP_GEN_HOTP_API_TC001 HOTP 9 #from RFC4226
/// C source: SDV_AUTH_OTP_GEN_HOTP_API_TC001 (line 40, HOTP generate KAT (RFC 4226))
#[test]
fn tc_line40_hotp_gen() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let hotp = Hotp::with_hash(secret, 6, OtpHashAlg::Sha1);
    assert_eq!(hotp.generate(9).unwrap(), 520489);
}

/// SDV_AUTH_OTP_GEN_TOTP_API_TC001 TOTP 59 SHA-1 #from RFC6238
/// C source: SDV_AUTH_OTP_GEN_TOTP_API_TC001 (line 43, TOTP generate KAT (RFC 6238))
#[test]
fn tc_line43_totp_gen() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let totp = Totp::with_hash(secret, 8, 30, OtpHashAlg::Sha1);
    assert_eq!(totp.generate(59).unwrap(), 94287082);
}

/// SDV_AUTH_OTP_GEN_TOTP_API_TC001 TOTP 59 SHA-256 #from RFC6238
/// C source: SDV_AUTH_OTP_GEN_TOTP_API_TC001 (line 45, TOTP generate KAT (RFC 6238))
#[test]
fn tc_line45_totp_gen() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30,
        0x31, 0x32,
    ];
    let totp = Totp::with_hash(secret, 8, 30, OtpHashAlg::Sha256);
    assert_eq!(totp.generate(59).unwrap(), 46119246);
}

/// SDV_AUTH_OTP_GEN_TOTP_API_TC001 TOTP 59 SHA-512 #from RFC6238
/// C source: SDV_AUTH_OTP_GEN_TOTP_API_TC001 (line 47, TOTP generate KAT (RFC 6238))
#[test]
fn tc_line47_totp_gen() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30,
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30,
        0x31, 0x32, 0x33, 0x34,
    ];
    let totp = Totp::with_hash(secret, 8, 30, OtpHashAlg::Sha512);
    assert_eq!(totp.generate(59).unwrap(), 90693936);
}

/// SDV_AUTH_OTP_GEN_TOTP_API_TC001 TOTP 1111111109 SHA-1 #from RFC6238
/// C source: SDV_AUTH_OTP_GEN_TOTP_API_TC001 (line 49, TOTP generate KAT (RFC 6238))
#[test]
fn tc_line49_totp_gen() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let totp = Totp::with_hash(secret, 8, 30, OtpHashAlg::Sha1);
    assert_eq!(totp.generate(1111111109).unwrap(), 7081804);
}

/// SDV_AUTH_OTP_GEN_TOTP_API_TC001 TOTP 1111111109 SHA-256 #from RFC6238
/// C source: SDV_AUTH_OTP_GEN_TOTP_API_TC001 (line 51, TOTP generate KAT (RFC 6238))
#[test]
fn tc_line51_totp_gen() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30,
        0x31, 0x32,
    ];
    let totp = Totp::with_hash(secret, 8, 30, OtpHashAlg::Sha256);
    assert_eq!(totp.generate(1111111109).unwrap(), 68084774);
}

/// SDV_AUTH_OTP_GEN_TOTP_API_TC001 TOTP 1111111109 SHA-512 #from RFC6238
/// C source: SDV_AUTH_OTP_GEN_TOTP_API_TC001 (line 53, TOTP generate KAT (RFC 6238))
#[test]
fn tc_line53_totp_gen() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30,
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30,
        0x31, 0x32, 0x33, 0x34,
    ];
    let totp = Totp::with_hash(secret, 8, 30, OtpHashAlg::Sha512);
    assert_eq!(totp.generate(1111111109).unwrap(), 25091201);
}

/// SDV_AUTH_OTP_GEN_TOTP_API_TC001 TOTP 1111111111 SHA-1 #from RFC6238
/// C source: SDV_AUTH_OTP_GEN_TOTP_API_TC001 (line 55, TOTP generate KAT (RFC 6238))
#[test]
fn tc_line55_totp_gen() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let totp = Totp::with_hash(secret, 8, 30, OtpHashAlg::Sha1);
    assert_eq!(totp.generate(1111111111).unwrap(), 14050471);
}

/// SDV_AUTH_OTP_GEN_TOTP_API_TC001 TOTP 1111111111 SHA-256 #from RFC6238
/// C source: SDV_AUTH_OTP_GEN_TOTP_API_TC001 (line 57, TOTP generate KAT (RFC 6238))
#[test]
fn tc_line57_totp_gen() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30,
        0x31, 0x32,
    ];
    let totp = Totp::with_hash(secret, 8, 30, OtpHashAlg::Sha256);
    assert_eq!(totp.generate(1111111111).unwrap(), 67062674);
}

/// SDV_AUTH_OTP_GEN_TOTP_API_TC001 TOTP 1111111111 SHA-512 #from RFC6238
/// C source: SDV_AUTH_OTP_GEN_TOTP_API_TC001 (line 59, TOTP generate KAT (RFC 6238))
#[test]
fn tc_line59_totp_gen() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30,
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30,
        0x31, 0x32, 0x33, 0x34,
    ];
    let totp = Totp::with_hash(secret, 8, 30, OtpHashAlg::Sha512);
    assert_eq!(totp.generate(1111111111).unwrap(), 99943326);
}

/// SDV_AUTH_OTP_GEN_TOTP_API_TC001 TOTP 1234567890 SHA-1 #from RFC6238
/// C source: SDV_AUTH_OTP_GEN_TOTP_API_TC001 (line 61, TOTP generate KAT (RFC 6238))
#[test]
fn tc_line61_totp_gen() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let totp = Totp::with_hash(secret, 8, 30, OtpHashAlg::Sha1);
    assert_eq!(totp.generate(1234567890).unwrap(), 89005924);
}

/// SDV_AUTH_OTP_GEN_TOTP_API_TC001 TOTP 1234567890 SHA-256 #from RFC6238
/// C source: SDV_AUTH_OTP_GEN_TOTP_API_TC001 (line 63, TOTP generate KAT (RFC 6238))
#[test]
fn tc_line63_totp_gen() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30,
        0x31, 0x32,
    ];
    let totp = Totp::with_hash(secret, 8, 30, OtpHashAlg::Sha256);
    assert_eq!(totp.generate(1234567890).unwrap(), 91819424);
}

/// SDV_AUTH_OTP_GEN_TOTP_API_TC001 TOTP 1234567890 SHA-512 #from RFC6238
/// C source: SDV_AUTH_OTP_GEN_TOTP_API_TC001 (line 65, TOTP generate KAT (RFC 6238))
#[test]
fn tc_line65_totp_gen() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30,
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30,
        0x31, 0x32, 0x33, 0x34,
    ];
    let totp = Totp::with_hash(secret, 8, 30, OtpHashAlg::Sha512);
    assert_eq!(totp.generate(1234567890).unwrap(), 93441116);
}

/// SDV_AUTH_OTP_GEN_TOTP_API_TC001 TOTP 2000000000 SHA-1 #from RFC6238
/// C source: SDV_AUTH_OTP_GEN_TOTP_API_TC001 (line 67, TOTP generate KAT (RFC 6238))
#[test]
fn tc_line67_totp_gen() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let totp = Totp::with_hash(secret, 8, 30, OtpHashAlg::Sha1);
    assert_eq!(totp.generate(2000000000).unwrap(), 69279037);
}

/// SDV_AUTH_OTP_GEN_TOTP_API_TC001 TOTP 2000000000 SHA-256 #from RFC6238
/// C source: SDV_AUTH_OTP_GEN_TOTP_API_TC001 (line 69, TOTP generate KAT (RFC 6238))
#[test]
fn tc_line69_totp_gen() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30,
        0x31, 0x32,
    ];
    let totp = Totp::with_hash(secret, 8, 30, OtpHashAlg::Sha256);
    assert_eq!(totp.generate(2000000000).unwrap(), 90698825);
}

/// SDV_AUTH_OTP_GEN_TOTP_API_TC001 TOTP 2000000000 SHA-512 #from RFC6238
/// C source: SDV_AUTH_OTP_GEN_TOTP_API_TC001 (line 71, TOTP generate KAT (RFC 6238))
#[test]
fn tc_line71_totp_gen() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30,
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30,
        0x31, 0x32, 0x33, 0x34,
    ];
    let totp = Totp::with_hash(secret, 8, 30, OtpHashAlg::Sha512);
    assert_eq!(totp.generate(2000000000).unwrap(), 38618901);
}

/// SDV_AUTH_OTP_GEN_TOTP_API_TC001 TOTP 20000000000 SHA-1 #from RFC6238
/// C source: SDV_AUTH_OTP_GEN_TOTP_API_TC001 (line 73, TOTP generate KAT (RFC 6238))
#[test]
fn tc_line73_totp_gen() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let totp = Totp::with_hash(secret, 8, 30, OtpHashAlg::Sha1);
    assert_eq!(totp.generate(20000000000).unwrap(), 65353130);
}

/// SDV_AUTH_OTP_GEN_TOTP_API_TC001 TOTP 20000000000 SHA-256 #from RFC6238
/// C source: SDV_AUTH_OTP_GEN_TOTP_API_TC001 (line 75, TOTP generate KAT (RFC 6238))
#[test]
fn tc_line75_totp_gen() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30,
        0x31, 0x32,
    ];
    let totp = Totp::with_hash(secret, 8, 30, OtpHashAlg::Sha256);
    assert_eq!(totp.generate(20000000000).unwrap(), 77737706);
}

/// SDV_AUTH_OTP_GEN_TOTP_API_TC001 TOTP 20000000000 SHA-512 #from RFC6238
/// C source: SDV_AUTH_OTP_GEN_TOTP_API_TC001 (line 77, TOTP generate KAT (RFC 6238))
#[test]
fn tc_line77_totp_gen() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30,
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30,
        0x31, 0x32, 0x33, 0x34,
    ];
    let totp = Totp::with_hash(secret, 8, 30, OtpHashAlg::Sha512);
    assert_eq!(totp.generate(20000000000).unwrap(), 47863826);
}

/// SDV_AUTH_OTP_GEN_TOTP_API_TC002 TOTP 2000000000 SHA-1 start from 2000-01-01 00:00:00 with time step size of 120
/// C source: SDV_AUTH_OTP_GEN_TOTP_API_TC002 (line 80, TOTP generate KAT (RFC 6238))
#[test]
fn tc_line80_totp_gen() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let totp = Totp::with_hash(secret, 8, 120, OtpHashAlg::Sha1);
    assert_eq!(totp.generate(1053315199).unwrap(), 66793220);
}

/// SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 HOTP right counter
/// C source: SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 (line 83, HOTP validate (RFC 4226))
#[test]
fn tc_line83_hotp_validate() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let hotp = Hotp::with_hash(secret, 6, OtpHashAlg::Sha1);
    assert!(hotp.verify(755224, 0).unwrap());
}

/// SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 HOTP counter + 4
/// C source: SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 (line 85, HOTP validate (RFC 4226))
#[test]
fn tc_line85_hotp_validate() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let hotp = Hotp::with_hash(secret, 6, OtpHashAlg::Sha1);
    assert!(!hotp.verify(338314, 0).unwrap());
}

/// SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 HOTP right counter
/// C source: SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 (line 87, HOTP validate (RFC 4226))
#[test]
fn tc_line87_hotp_validate() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let hotp = Hotp::with_hash(secret, 6, OtpHashAlg::Sha1);
    assert!(hotp.verify(287082, 1).unwrap());
}

/// SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 HOTP counter + 3
/// C source: SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 (line 89, HOTP validate (RFC 4226))
#[test]
fn tc_line89_hotp_validate() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let hotp = Hotp::with_hash(secret, 6, OtpHashAlg::Sha1);
    assert!(!hotp.verify(338314, 1).unwrap());
}

/// SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 HOTP right counter
/// C source: SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 (line 91, HOTP validate (RFC 4226))
#[test]
fn tc_line91_hotp_validate() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let hotp = Hotp::with_hash(secret, 6, OtpHashAlg::Sha1);
    assert!(hotp.verify(359152, 2).unwrap());
}

/// SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 HOTP counter + 2
/// C source: SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 (line 93, HOTP validate (RFC 4226))
#[test]
fn tc_line93_hotp_validate() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let hotp = Hotp::with_hash(secret, 6, OtpHashAlg::Sha1);
    assert!(!hotp.verify(338314, 2).unwrap());
}

/// SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 HOTP right counter
/// C source: SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 (line 95, HOTP validate (RFC 4226))
#[test]
fn tc_line95_hotp_validate() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let hotp = Hotp::with_hash(secret, 6, OtpHashAlg::Sha1);
    assert!(hotp.verify(969429, 3).unwrap());
}

/// SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 HOTP counter + 1
/// C source: SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 (line 97, HOTP validate (RFC 4226))
#[test]
fn tc_line97_hotp_validate() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let hotp = Hotp::with_hash(secret, 6, OtpHashAlg::Sha1);
    assert!(!hotp.verify(338314, 3).unwrap());
}

/// SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 HOTP right counter
/// C source: SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 (line 99, HOTP validate (RFC 4226))
#[test]
fn tc_line99_hotp_validate() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let hotp = Hotp::with_hash(secret, 6, OtpHashAlg::Sha1);
    assert!(hotp.verify(338314, 4).unwrap());
}

/// SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 HOTP random
/// C source: SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 (line 101, HOTP validate (RFC 4226))
#[test]
fn tc_line101_hotp_validate() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let hotp = Hotp::with_hash(secret, 6, OtpHashAlg::Sha1);
    assert!(!hotp.verify(338315, 4).unwrap());
}

/// SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 HOTP right counter
/// C source: SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 (line 103, HOTP validate (RFC 4226))
#[test]
fn tc_line103_hotp_validate() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let hotp = Hotp::with_hash(secret, 6, OtpHashAlg::Sha1);
    assert!(hotp.verify(254676, 5).unwrap());
}

/// SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 HOTP mismatch length
/// C source: SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 (line 105, HOTP validate (RFC 4226))
#[test]
fn tc_line105_hotp_validate() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let hotp = Hotp::with_hash(secret, 6, OtpHashAlg::Sha1);
    assert!(!hotp.verify(68254676, 5).unwrap());
}

/// SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 HOTP right counter
/// C source: SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 (line 107, HOTP validate (RFC 4226))
#[test]
fn tc_line107_hotp_validate() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let hotp = Hotp::with_hash(secret, 6, OtpHashAlg::Sha1);
    assert!(hotp.verify(287922, 6).unwrap());
}

/// SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 HOTP counter - 1
/// C source: SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 (line 109, HOTP validate (RFC 4226))
#[test]
fn tc_line109_hotp_validate() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let hotp = Hotp::with_hash(secret, 6, OtpHashAlg::Sha1);
    assert!(!hotp.verify(254676, 6).unwrap());
}

/// SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 HOTP right counter
/// C source: SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 (line 111, HOTP validate (RFC 4226))
#[test]
fn tc_line111_hotp_validate() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let hotp = Hotp::with_hash(secret, 6, OtpHashAlg::Sha1);
    assert!(hotp.verify(162583, 7).unwrap());
}

/// SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 HOTP counter - 2
/// C source: SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 (line 113, HOTP validate (RFC 4226))
#[test]
fn tc_line113_hotp_validate() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let hotp = Hotp::with_hash(secret, 6, OtpHashAlg::Sha1);
    assert!(!hotp.verify(254676, 7).unwrap());
}

/// SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 HOTP right counter
/// C source: SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 (line 115, HOTP validate (RFC 4226))
#[test]
fn tc_line115_hotp_validate() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let hotp = Hotp::with_hash(secret, 6, OtpHashAlg::Sha1);
    assert!(hotp.verify(399871, 8).unwrap());
}

/// SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 HOTP counter - 3
/// C source: SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 (line 117, HOTP validate (RFC 4226))
#[test]
fn tc_line117_hotp_validate() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let hotp = Hotp::with_hash(secret, 6, OtpHashAlg::Sha1);
    assert!(!hotp.verify(254676, 8).unwrap());
}

/// SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 HOTP right counter
/// C source: SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 (line 119, HOTP validate (RFC 4226))
#[test]
fn tc_line119_hotp_validate() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let hotp = Hotp::with_hash(secret, 6, OtpHashAlg::Sha1);
    assert!(hotp.verify(520489, 9).unwrap());
}

/// SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 HOTP counter - 4
/// C source: SDV_AUTH_OTP_VALIDATE_HOTP_API_TC001 (line 121, HOTP validate (RFC 4226))
#[test]
fn tc_line121_hotp_validate() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let hotp = Hotp::with_hash(secret, 6, OtpHashAlg::Sha1);
    assert!(!hotp.verify(254676, 9).unwrap());
}

/// SDV_AUTH_OTP_VALIDATE_TOTP_API_TC002 TOTP right counter and valid window of 0
/// C source: SDV_AUTH_OTP_VALIDATE_TOTP_API_TC002 (line 173, TOTP validate (RFC 6238, validWindow in row))
#[test]
fn tc_line173_totp_validate() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let totp = Totp::with_hash(secret, 8, 120, OtpHashAlg::Sha1);
    assert!(totp.verify(66793220, 1053315199, 0).unwrap());
}

/// SDV_AUTH_OTP_VALIDATE_TOTP_API_TC002 TOTP counter - 1 and valid window of 0
/// C source: SDV_AUTH_OTP_VALIDATE_TOTP_API_TC002 (line 175, TOTP validate (RFC 6238, validWindow in row))
#[test]
fn tc_line175_totp_validate() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let totp = Totp::with_hash(secret, 8, 120, OtpHashAlg::Sha1);
    assert!(!totp.verify(75363862, 1053315199, 0).unwrap());
}

/// SDV_AUTH_OTP_VALIDATE_TOTP_API_TC002 TOTP counter + 1 and valid window of 0
/// C source: SDV_AUTH_OTP_VALIDATE_TOTP_API_TC002 (line 177, TOTP validate (RFC 6238, validWindow in row))
#[test]
fn tc_line177_totp_validate() {
    let secret: &[u8] = &[
        0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35,
        0x36, 0x37, 0x38, 0x39, 0x30,
    ];
    let totp = Totp::with_hash(secret, 8, 120, OtpHashAlg::Sha1);
    assert!(!totp.verify(59110814, 1053315199, 0).unwrap());
}

// Generation summary: 52 emitted / 32 API-surface skipped (N/A in Rust) / 0 unknown / 84 total C cases.
