//! CMAC (Cipher-based Message Authentication Code) implementation.
//!
//! CMAC provides message authentication using a 128-bit block cipher per
//! **NIST SP 800-38B** / **RFC 4493**. This module ships two concrete
//! contexts:
//!
//! - [`Cmac`] — over AES (any key length).
//! - [`CmacSm4`] — over SM4 (gated by the `sm4` Cargo feature).
//!
//! Both have an identical algorithmic body (Rb = `0x87`, K1 / K2 derived
//! from `E_K(0^n)` via `dbl`, 10*-padding for partial last block); they
//! differ only in the block-cipher primitive plugged in. The shared body
//! is generated by the internal `define_cmac!` macro to keep them
//! byte-identical.

use crate::aes::{AesKey, AES_BLOCK_SIZE};
#[cfg(feature = "sm4")]
use crate::sm4::Sm4Key;
use hitls_types::CryptoError;
use zeroize::Zeroize;

/// CMAC block size in bytes (16 — both AES and SM4 use a 128-bit block).
const BLOCK_SIZE: usize = AES_BLOCK_SIZE;

/// Left-shift a 128-bit block by 1 bit; if MSB was 1, XOR with Rb (0x87).
fn dbl(block: &[u8; BLOCK_SIZE]) -> [u8; BLOCK_SIZE] {
    let mut result = [0u8; BLOCK_SIZE];
    let mut carry = 0u8;
    for i in (0..BLOCK_SIZE).rev() {
        result[i] = (block[i] << 1) | carry;
        carry = block[i] >> 7;
    }
    if block[0] & 0x80 != 0 {
        result[BLOCK_SIZE - 1] ^= 0x87;
    }
    result
}

/// Generate a CMAC context type over a specific 128-bit block cipher.
///
/// `$cipher` must expose `fn new(&[u8]) -> Result<Self, CryptoError>` and
/// `fn encrypt_block(&self, &mut [u8]) -> Result<(), CryptoError>` (both
/// `AesKey` and `Sm4Key` do).
macro_rules! define_cmac {
    ($(#[$meta:meta])* $name:ident, $cipher:ty) => {
        $(#[$meta])*
        pub struct $name {
            cipher: $cipher,
            /// Subkey K1 derived from the block cipher.
            k1: [u8; BLOCK_SIZE],
            /// Subkey K2 derived from the block cipher.
            k2: [u8; BLOCK_SIZE],
            /// CBC chain value.
            state: [u8; BLOCK_SIZE],
            /// Buffer for incomplete block.
            buf: [u8; BLOCK_SIZE],
            buf_len: usize,
        }

        impl Drop for $name {
            fn drop(&mut self) {
                self.k1.zeroize();
                self.k2.zeroize();
                self.state.zeroize();
                self.buf.zeroize();
            }
        }

        impl $name {
            /// Create a new CMAC instance with the given key.
            pub fn new(key: &[u8]) -> Result<Self, CryptoError> {
                let cipher = <$cipher>::new(key)?;

                // L = E_K(0^n)
                let mut l = [0u8; BLOCK_SIZE];
                cipher.encrypt_block(&mut l)?;

                let k1 = dbl(&l);
                let k2 = dbl(&k1);

                l.zeroize();

                Ok($name {
                    cipher,
                    k1,
                    k2,
                    state: [0u8; BLOCK_SIZE],
                    buf: [0u8; BLOCK_SIZE],
                    buf_len: 0,
                })
            }

            /// Feed data into the CMAC computation.
            pub fn update(&mut self, data: &[u8]) -> Result<(), CryptoError> {
                let mut pos = 0;

                // Fill buffer.
                if self.buf_len > 0 {
                    let want = BLOCK_SIZE - self.buf_len;
                    if data.len() <= want {
                        self.buf[self.buf_len..self.buf_len + data.len()].copy_from_slice(data);
                        self.buf_len += data.len();
                        return Ok(());
                    }
                    self.buf[self.buf_len..BLOCK_SIZE].copy_from_slice(&data[..want]);
                    pos = want;
                    self.buf_len = BLOCK_SIZE;
                }

                // Process full blocks, but always keep last block in buffer.
                while pos + BLOCK_SIZE < data.len()
                    || (pos < data.len() && self.buf_len == BLOCK_SIZE)
                {
                    if self.buf_len == BLOCK_SIZE {
                        for (s, &b) in self.state.iter_mut().zip(self.buf.iter()) {
                            *s ^= b;
                        }
                        self.cipher.encrypt_block(&mut self.state)?;
                        self.buf_len = 0;
                    }

                    if pos + BLOCK_SIZE < data.len() {
                        for (s, &d) in self
                            .state
                            .iter_mut()
                            .zip(data[pos..pos + BLOCK_SIZE].iter())
                        {
                            *s ^= d;
                        }
                        self.cipher.encrypt_block(&mut self.state)?;
                        pos += BLOCK_SIZE;
                    } else {
                        break;
                    }
                }

                // Buffer remaining data.
                if pos < data.len() {
                    let remaining = data.len() - pos;
                    if self.buf_len == BLOCK_SIZE {
                        for (s, &b) in self.state.iter_mut().zip(self.buf.iter()) {
                            *s ^= b;
                        }
                        self.cipher.encrypt_block(&mut self.state)?;
                        self.buf_len = 0;
                    }
                    self.buf[..remaining].copy_from_slice(&data[pos..]);
                    self.buf_len = remaining;
                }

                Ok(())
            }

            /// Finalize the CMAC computation and write the result to `out`.
            pub fn finish(&mut self, out: &mut [u8]) -> Result<(), CryptoError> {
                if out.len() < BLOCK_SIZE {
                    return Err(CryptoError::InvalidArg(""));
                }

                let mut last_block = [0u8; BLOCK_SIZE];

                if self.buf_len == BLOCK_SIZE {
                    // Complete block: XOR with K1.
                    for (lb, (&b, &k)) in last_block
                        .iter_mut()
                        .zip(self.buf.iter().zip(self.k1.iter()))
                    {
                        *lb = b ^ k;
                    }
                } else {
                    // Incomplete block: pad with 10* and XOR with K2.
                    last_block[..self.buf_len].copy_from_slice(&self.buf[..self.buf_len]);
                    last_block[self.buf_len] = 0x80;
                    for (lb, &k) in last_block.iter_mut().zip(self.k2.iter()) {
                        *lb ^= k;
                    }
                }

                for (s, &b) in self.state.iter_mut().zip(last_block.iter()) {
                    *s ^= b;
                }
                self.cipher.encrypt_block(&mut self.state)?;

                out[..BLOCK_SIZE].copy_from_slice(&self.state);
                Ok(())
            }

            /// Reset the CMAC state for reuse with the same key.
            pub fn reset(&mut self) {
                self.state = [0u8; BLOCK_SIZE];
                self.buf = [0u8; BLOCK_SIZE];
                self.buf_len = 0;
            }
        }
    };
}

define_cmac!(
    /// CMAC over AES (NIST SP 800-38B / RFC 4493). Any AES key length.
    Cmac,
    AesKey
);

#[cfg(feature = "sm4")]
define_cmac!(
    /// CMAC over SM4 (GB/T 15852.1-2020 / mirroring NIST SP 800-38B; SM4
    /// shares the 128-bit block size + the same Rb = 0x87 lookup).
    CmacSm4,
    Sm4Key
);

#[cfg(test)]
mod tests {
    use super::*;
    use hitls_utils::hex::{hex, to_hex};

    // RFC 4493 Test Vectors for AES-CMAC with 128-bit key
    // Key: 2b7e1516 28aed2a6 abf71588 09cf4f3c

    #[test]
    fn test_cmac_rfc4493_empty() {
        let key = hex("2b7e151628aed2a6abf7158809cf4f3c");
        let mut cmac = Cmac::new(&key).unwrap();
        cmac.update(&[]).unwrap();
        let mut tag = [0u8; 16];
        cmac.finish(&mut tag).unwrap();
        assert_eq!(to_hex(&tag), "bb1d6929e95937287fa37d129b756746");
    }

    #[test]
    fn test_cmac_rfc4493_16bytes() {
        let key = hex("2b7e151628aed2a6abf7158809cf4f3c");
        let msg = hex("6bc1bee22e409f96e93d7e117393172a");
        let mut cmac = Cmac::new(&key).unwrap();
        cmac.update(&msg).unwrap();
        let mut tag = [0u8; 16];
        cmac.finish(&mut tag).unwrap();
        assert_eq!(to_hex(&tag), "070a16b46b4d4144f79bdd9dd04a287c");
    }

    #[test]
    fn test_cmac_rfc4493_40bytes() {
        let key = hex("2b7e151628aed2a6abf7158809cf4f3c");
        let msg =
            hex("6bc1bee22e409f96e93d7e117393172aae2d8a571e03ac9c9eb76fac45af8e5130c81c46a35ce411");
        let mut cmac = Cmac::new(&key).unwrap();
        cmac.update(&msg).unwrap();
        let mut tag = [0u8; 16];
        cmac.finish(&mut tag).unwrap();
        assert_eq!(to_hex(&tag), "dfa66747de9ae63030ca32611497c827");
    }

    #[test]
    fn test_cmac_rfc4493_64bytes() {
        let key = hex("2b7e151628aed2a6abf7158809cf4f3c");
        let msg = hex("6bc1bee22e409f96e93d7e117393172aae2d8a571e03ac9c9eb76fac45af8e5130c81c46a35ce411e5fbc1191a0a52eff69f2445df4f9b17ad2b417be66c3710");
        let mut cmac = Cmac::new(&key).unwrap();
        cmac.update(&msg).unwrap();
        let mut tag = [0u8; 16];
        cmac.finish(&mut tag).unwrap();
        assert_eq!(to_hex(&tag), "51f0bebf7e3b9d92fc49741779363cfe");
    }

    #[test]
    fn test_cmac_reset() {
        let key = hex("2b7e151628aed2a6abf7158809cf4f3c");
        let mut cmac = Cmac::new(&key).unwrap();

        // First computation
        cmac.update(&[]).unwrap();
        let mut tag1 = [0u8; 16];
        cmac.finish(&mut tag1).unwrap();

        // Reset and do again
        cmac.reset();
        cmac.update(&[]).unwrap();
        let mut tag2 = [0u8; 16];
        cmac.finish(&mut tag2).unwrap();

        assert_eq!(tag1, tag2);
    }

    // NIST SP 800-38B D.3: AES-256 CMAC empty message
    #[test]
    fn test_cmac_aes256_nist_sp800_38b() {
        let key = hex("603deb1015ca71be2b73aef0857d77811f352c073b6108d72d9810a30914dff4");
        let mut cmac = Cmac::new(&key).unwrap();
        cmac.update(&[]).unwrap();
        let mut tag = [0u8; 16];
        cmac.finish(&mut tag).unwrap();
        assert_eq!(to_hex(&tag), "028962f61b7bf89efc6b551f4667d983");
    }

    // RFC 4493 64-byte message fed incrementally in various chunk sizes
    #[test]
    fn test_cmac_incremental_various_splits() {
        let key = hex("2b7e151628aed2a6abf7158809cf4f3c");
        let msg = hex("6bc1bee22e409f96e93d7e117393172aae2d8a571e03ac9c9eb76fac45af8e5130c81c46a35ce411e5fbc1191a0a52eff69f2445df4f9b17ad2b417be66c3710");
        let expected = "51f0bebf7e3b9d92fc49741779363cfe";

        // Feed in chunks of varying sizes: 1, 7, 17, ...
        for chunk_size in [1, 7, 17] {
            let mut cmac = Cmac::new(&key).unwrap();
            for chunk in msg.chunks(chunk_size) {
                cmac.update(chunk).unwrap();
            }
            let mut tag = [0u8; 16];
            cmac.finish(&mut tag).unwrap();
            assert_eq!(
                to_hex(&tag),
                expected,
                "tag mismatch for chunk_size={chunk_size}"
            );
        }
    }

    #[test]
    fn test_cmac_finish_output_too_small() {
        let key = hex("2b7e151628aed2a6abf7158809cf4f3c");
        let mut cmac = Cmac::new(&key).unwrap();
        cmac.update(b"data").unwrap();
        let mut small_buf = [0u8; 8];
        assert!(cmac.finish(&mut small_buf).is_err());
    }

    mod proptests {
        use super::*;
        use proptest::prelude::*;

        proptest! {
            #![proptest_config(ProptestConfig::with_cases(20))]

            #[test]
            fn prop_cmac_incremental_equiv(
                key in prop::array::uniform16(any::<u8>()),
                a in proptest::collection::vec(any::<u8>(), 0..64),
                b in proptest::collection::vec(any::<u8>(), 0..64),
            ) {
                let mut combined = a.clone();
                combined.extend_from_slice(&b);

                // One-shot
                let mut oneshot = Cmac::new(&key).unwrap();
                oneshot.update(&combined).unwrap();
                let mut tag1 = [0u8; 16];
                oneshot.finish(&mut tag1).unwrap();

                // Incremental
                let mut incr = Cmac::new(&key).unwrap();
                incr.update(&a).unwrap();
                incr.update(&b).unwrap();
                let mut tag2 = [0u8; 16];
                incr.finish(&mut tag2).unwrap();

                prop_assert_eq!(tag1, tag2);
            }
        }
    }
}
